// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module solve_top_decompose_qr_Pipeline_VITIS_LOOP_77_10 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        QT_out_0_0,
        QT_out_0_0_ap_vld,
        QT_out_1_0,
        QT_out_1_0_ap_vld,
        QT_out_2_0,
        QT_out_2_0_ap_vld,
        QT_out_3_0,
        QT_out_3_0_ap_vld,
        QT_out_3_3,
        QT_out_3_3_ap_vld,
        QT_out_3_2,
        QT_out_3_2_ap_vld,
        QT_out_3_1,
        QT_out_3_1_ap_vld,
        QT_out_2_3,
        QT_out_2_3_ap_vld,
        QT_out_2_2,
        QT_out_2_2_ap_vld,
        QT_out_2_1,
        QT_out_2_1_ap_vld,
        QT_out_1_3,
        QT_out_1_3_ap_vld,
        QT_out_1_2,
        QT_out_1_2_ap_vld,
        QT_out_1_1,
        QT_out_1_1_ap_vld,
        QT_out_0_3,
        QT_out_0_3_ap_vld,
        QT_out_0_2,
        QT_out_0_2_ap_vld,
        QT_out_0_1,
        QT_out_0_1_ap_vld,
        local_aug_16_load,
        local_aug_17_load,
        local_aug_18_load,
        local_aug_19_load,
        local_aug_20_load,
        local_aug_21_load,
        local_aug_22_load,
        local_aug_23_load,
        local_aug_24_load,
        local_aug_25_load,
        local_aug_26_load,
        local_aug_27_load,
        local_aug_28_load,
        local_aug_29_load,
        local_aug_30_load,
        local_aug_31_load
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] QT_out_0_0;
output   QT_out_0_0_ap_vld;
output  [15:0] QT_out_1_0;
output   QT_out_1_0_ap_vld;
output  [15:0] QT_out_2_0;
output   QT_out_2_0_ap_vld;
output  [15:0] QT_out_3_0;
output   QT_out_3_0_ap_vld;
output  [15:0] QT_out_3_3;
output   QT_out_3_3_ap_vld;
output  [15:0] QT_out_3_2;
output   QT_out_3_2_ap_vld;
output  [15:0] QT_out_3_1;
output   QT_out_3_1_ap_vld;
output  [15:0] QT_out_2_3;
output   QT_out_2_3_ap_vld;
output  [15:0] QT_out_2_2;
output   QT_out_2_2_ap_vld;
output  [15:0] QT_out_2_1;
output   QT_out_2_1_ap_vld;
output  [15:0] QT_out_1_3;
output   QT_out_1_3_ap_vld;
output  [15:0] QT_out_1_2;
output   QT_out_1_2_ap_vld;
output  [15:0] QT_out_1_1;
output   QT_out_1_1_ap_vld;
output  [15:0] QT_out_0_3;
output   QT_out_0_3_ap_vld;
output  [15:0] QT_out_0_2;
output   QT_out_0_2_ap_vld;
output  [15:0] QT_out_0_1;
output   QT_out_0_1_ap_vld;
input  [15:0] local_aug_16_load;
input  [15:0] local_aug_17_load;
input  [15:0] local_aug_18_load;
input  [15:0] local_aug_19_load;
input  [15:0] local_aug_20_load;
input  [15:0] local_aug_21_load;
input  [15:0] local_aug_22_load;
input  [15:0] local_aug_23_load;
input  [15:0] local_aug_24_load;
input  [15:0] local_aug_25_load;
input  [15:0] local_aug_26_load;
input  [15:0] local_aug_27_load;
input  [15:0] local_aug_28_load;
input  [15:0] local_aug_29_load;
input  [15:0] local_aug_30_load;
input  [15:0] local_aug_31_load;

reg ap_idle;
reg QT_out_0_0_ap_vld;
reg QT_out_1_0_ap_vld;
reg QT_out_2_0_ap_vld;
reg QT_out_3_0_ap_vld;
reg QT_out_3_3_ap_vld;
reg QT_out_3_2_ap_vld;
reg QT_out_3_1_ap_vld;
reg QT_out_2_3_ap_vld;
reg QT_out_2_2_ap_vld;
reg QT_out_2_1_ap_vld;
reg QT_out_1_3_ap_vld;
reg QT_out_1_2_ap_vld;
reg QT_out_1_1_ap_vld;
reg QT_out_0_3_ap_vld;
reg QT_out_0_2_ap_vld;
reg QT_out_0_1_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln77_fu_324_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] r_fu_104;
wire   [2:0] add_ln77_fu_330_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_r_1;
wire   [15:0] tmp_s_fu_340_p11;
wire   [1:0] trunc_ln77_fu_336_p1;
wire   [15:0] tmp_174_fu_368_p11;
wire   [15:0] tmp_175_fu_396_p11;
wire   [15:0] tmp_176_fu_424_p11;
wire   [15:0] tmp_s_fu_340_p9;
wire   [15:0] tmp_174_fu_368_p9;
wire   [15:0] tmp_175_fu_396_p9;
wire   [15:0] tmp_176_fu_424_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_s_fu_340_p1;
wire   [1:0] tmp_s_fu_340_p3;
wire  signed [1:0] tmp_s_fu_340_p5;
wire  signed [1:0] tmp_s_fu_340_p7;
wire   [1:0] tmp_174_fu_368_p1;
wire   [1:0] tmp_174_fu_368_p3;
wire  signed [1:0] tmp_174_fu_368_p5;
wire  signed [1:0] tmp_174_fu_368_p7;
wire   [1:0] tmp_175_fu_396_p1;
wire   [1:0] tmp_175_fu_396_p3;
wire  signed [1:0] tmp_175_fu_396_p5;
wire  signed [1:0] tmp_175_fu_396_p7;
wire   [1:0] tmp_176_fu_424_p1;
wire   [1:0] tmp_176_fu_424_p3;
wire  signed [1:0] tmp_176_fu_424_p5;
wire  signed [1:0] tmp_176_fu_424_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 r_fu_104 = 3'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U214(
    .din0(local_aug_16_load),
    .din1(local_aug_17_load),
    .din2(local_aug_18_load),
    .din3(local_aug_19_load),
    .def(tmp_s_fu_340_p9),
    .sel(trunc_ln77_fu_336_p1),
    .dout(tmp_s_fu_340_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U215(
    .din0(local_aug_20_load),
    .din1(local_aug_21_load),
    .din2(local_aug_22_load),
    .din3(local_aug_23_load),
    .def(tmp_174_fu_368_p9),
    .sel(trunc_ln77_fu_336_p1),
    .dout(tmp_174_fu_368_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U216(
    .din0(local_aug_24_load),
    .din1(local_aug_25_load),
    .din2(local_aug_26_load),
    .din3(local_aug_27_load),
    .def(tmp_175_fu_396_p9),
    .sel(trunc_ln77_fu_336_p1),
    .dout(tmp_175_fu_396_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U217(
    .din0(local_aug_28_load),
    .din1(local_aug_29_load),
    .din2(local_aug_30_load),
    .din3(local_aug_31_load),
    .def(tmp_176_fu_424_p9),
    .sel(trunc_ln77_fu_336_p1),
    .dout(tmp_176_fu_424_p11)
);

solve_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln77_fu_324_p2 == 1'd0)) begin
            r_fu_104 <= add_ln77_fu_330_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_104 <= 3'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd0))) begin
        QT_out_0_0_ap_vld = 1'b1;
    end else begin
        QT_out_0_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd1))) begin
        QT_out_0_1_ap_vld = 1'b1;
    end else begin
        QT_out_0_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd2))) begin
        QT_out_0_2_ap_vld = 1'b1;
    end else begin
        QT_out_0_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd3))) begin
        QT_out_0_3_ap_vld = 1'b1;
    end else begin
        QT_out_0_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd0))) begin
        QT_out_1_0_ap_vld = 1'b1;
    end else begin
        QT_out_1_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd1))) begin
        QT_out_1_1_ap_vld = 1'b1;
    end else begin
        QT_out_1_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd2))) begin
        QT_out_1_2_ap_vld = 1'b1;
    end else begin
        QT_out_1_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd3))) begin
        QT_out_1_3_ap_vld = 1'b1;
    end else begin
        QT_out_1_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd0))) begin
        QT_out_2_0_ap_vld = 1'b1;
    end else begin
        QT_out_2_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd1))) begin
        QT_out_2_1_ap_vld = 1'b1;
    end else begin
        QT_out_2_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd2))) begin
        QT_out_2_2_ap_vld = 1'b1;
    end else begin
        QT_out_2_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd3))) begin
        QT_out_2_3_ap_vld = 1'b1;
    end else begin
        QT_out_2_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd0))) begin
        QT_out_3_0_ap_vld = 1'b1;
    end else begin
        QT_out_3_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd1))) begin
        QT_out_3_1_ap_vld = 1'b1;
    end else begin
        QT_out_3_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd2))) begin
        QT_out_3_2_ap_vld = 1'b1;
    end else begin
        QT_out_3_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln77_fu_336_p1 == 2'd3))) begin
        QT_out_3_3_ap_vld = 1'b1;
    end else begin
        QT_out_3_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_324_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_r_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_r_1 = r_fu_104;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign QT_out_0_0 = tmp_s_fu_340_p11;

assign QT_out_0_1 = tmp_s_fu_340_p11;

assign QT_out_0_2 = tmp_s_fu_340_p11;

assign QT_out_0_3 = tmp_s_fu_340_p11;

assign QT_out_1_0 = tmp_174_fu_368_p11;

assign QT_out_1_1 = tmp_174_fu_368_p11;

assign QT_out_1_2 = tmp_174_fu_368_p11;

assign QT_out_1_3 = tmp_174_fu_368_p11;

assign QT_out_2_0 = tmp_175_fu_396_p11;

assign QT_out_2_1 = tmp_175_fu_396_p11;

assign QT_out_2_2 = tmp_175_fu_396_p11;

assign QT_out_2_3 = tmp_175_fu_396_p11;

assign QT_out_3_0 = tmp_176_fu_424_p11;

assign QT_out_3_1 = tmp_176_fu_424_p11;

assign QT_out_3_2 = tmp_176_fu_424_p11;

assign QT_out_3_3 = tmp_176_fu_424_p11;

assign add_ln77_fu_330_p2 = (ap_sig_allocacmp_r_1 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln77_fu_324_p2 = ((ap_sig_allocacmp_r_1 == 3'd4) ? 1'b1 : 1'b0);

assign tmp_174_fu_368_p9 = 'bx;

assign tmp_175_fu_396_p9 = 'bx;

assign tmp_176_fu_424_p9 = 'bx;

assign tmp_s_fu_340_p9 = 'bx;

assign trunc_ln77_fu_336_p1 = ap_sig_allocacmp_r_1[1:0];

endmodule //solve_top_decompose_qr_Pipeline_VITIS_LOOP_77_10
