// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module solve_top_decompose_qr_Pipeline_VITIS_LOOP_63_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_217,
        tmp_216,
        tmp_215,
        tmp_214,
        tmp_202,
        tmp_201,
        tmp_200,
        tmp_199,
        local_aug_47_out,
        local_aug_47_out_ap_vld,
        local_aug_46_out,
        local_aug_46_out_ap_vld,
        local_aug_45_out,
        local_aug_45_out_ap_vld,
        local_aug_44_out,
        local_aug_44_out_ap_vld,
        local_aug_43_out,
        local_aug_43_out_ap_vld,
        local_aug_42_out,
        local_aug_42_out_ap_vld,
        local_aug_41_out,
        local_aug_41_out_ap_vld,
        local_aug_40_out,
        local_aug_40_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] tmp_217;
input  [15:0] tmp_216;
input  [15:0] tmp_215;
input  [15:0] tmp_214;
input  [15:0] tmp_202;
input  [15:0] tmp_201;
input  [15:0] tmp_200;
input  [15:0] tmp_199;
output  [15:0] local_aug_47_out;
output   local_aug_47_out_ap_vld;
output  [15:0] local_aug_46_out;
output   local_aug_46_out_ap_vld;
output  [15:0] local_aug_45_out;
output   local_aug_45_out_ap_vld;
output  [15:0] local_aug_44_out;
output   local_aug_44_out_ap_vld;
output  [15:0] local_aug_43_out;
output   local_aug_43_out_ap_vld;
output  [15:0] local_aug_42_out;
output   local_aug_42_out_ap_vld;
output  [15:0] local_aug_41_out;
output   local_aug_41_out_ap_vld;
output  [15:0] local_aug_40_out;
output   local_aug_40_out_ap_vld;

reg ap_idle;
reg local_aug_47_out_ap_vld;
reg local_aug_46_out_ap_vld;
reg local_aug_45_out_ap_vld;
reg local_aug_44_out_ap_vld;
reg local_aug_43_out_ap_vld;
reg local_aug_42_out_ap_vld;
reg local_aug_41_out_ap_vld;
reg local_aug_40_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln63_fu_282_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] trunc_ln63_fu_294_p1;
reg   [2:0] trunc_ln63_reg_594;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] c_fu_94;
wire   [3:0] add_ln63_fu_288_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_c_1;
wire    ap_block_pp0_stage0;
reg   [15:0] local_aug_40_fu_98;
wire   [15:0] select_ln64_1_fu_440_p3;
reg   [15:0] local_aug_41_fu_102;
reg   [15:0] local_aug_42_fu_106;
reg   [15:0] local_aug_43_fu_110;
reg   [15:0] local_aug_44_fu_114;
reg   [15:0] local_aug_45_fu_118;
reg   [15:0] local_aug_46_fu_122;
reg   [15:0] local_aug_47_fu_126;
wire    ap_block_pp0_stage0_01001;
wire   [15:0] tmp_s_fu_345_p17;
wire   [15:0] tmp_s_fu_345_p19;
wire  signed [16:0] sext_ln64_fu_384_p1;
wire   [16:0] sub_ln64_fu_388_p2;
wire   [0:0] tmp_fu_394_p3;
wire   [0:0] tmp_229_fu_406_p3;
wire   [0:0] xor_ln64_fu_414_p2;
wire   [0:0] and_ln64_fu_420_p2;
wire   [0:0] xor_ln64_1_fu_426_p2;
wire   [15:0] select_ln64_fu_432_p3;
wire   [15:0] trunc_ln64_fu_402_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_s_fu_345_p1;
wire   [2:0] tmp_s_fu_345_p3;
wire   [2:0] tmp_s_fu_345_p5;
wire   [2:0] tmp_s_fu_345_p7;
wire  signed [2:0] tmp_s_fu_345_p9;
wire  signed [2:0] tmp_s_fu_345_p11;
wire  signed [2:0] tmp_s_fu_345_p13;
wire  signed [2:0] tmp_s_fu_345_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 c_fu_94 = 4'd0;
#0 local_aug_40_fu_98 = 16'd0;
#0 local_aug_41_fu_102 = 16'd0;
#0 local_aug_42_fu_106 = 16'd0;
#0 local_aug_43_fu_110 = 16'd0;
#0 local_aug_44_fu_114 = 16'd0;
#0 local_aug_45_fu_118 = 16'd0;
#0 local_aug_46_fu_122 = 16'd0;
#0 local_aug_47_fu_126 = 16'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U159(
    .din0(local_aug_40_fu_98),
    .din1(local_aug_41_fu_102),
    .din2(local_aug_42_fu_106),
    .din3(local_aug_43_fu_110),
    .din4(local_aug_44_fu_114),
    .din5(local_aug_45_fu_118),
    .din6(local_aug_46_fu_122),
    .din7(local_aug_47_fu_126),
    .def(tmp_s_fu_345_p17),
    .sel(trunc_ln63_reg_594),
    .dout(tmp_s_fu_345_p19)
);

solve_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln63_fu_282_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_94 <= add_ln63_fu_288_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_94 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_aug_40_fu_98 <= tmp_199;
        end else if (((trunc_ln63_reg_594 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            local_aug_40_fu_98 <= select_ln64_1_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_aug_41_fu_102 <= tmp_200;
        end else if (((trunc_ln63_reg_594 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            local_aug_41_fu_102 <= select_ln64_1_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_aug_42_fu_106 <= tmp_201;
        end else if (((trunc_ln63_reg_594 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            local_aug_42_fu_106 <= select_ln64_1_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_aug_43_fu_110 <= tmp_202;
        end else if (((trunc_ln63_reg_594 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            local_aug_43_fu_110 <= select_ln64_1_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_aug_44_fu_114 <= tmp_214;
        end else if (((trunc_ln63_reg_594 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            local_aug_44_fu_114 <= select_ln64_1_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_aug_45_fu_118 <= tmp_215;
        end else if (((trunc_ln63_reg_594 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            local_aug_45_fu_118 <= select_ln64_1_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_aug_46_fu_122 <= tmp_216;
        end else if (((trunc_ln63_reg_594 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            local_aug_46_fu_122 <= select_ln64_1_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_aug_47_fu_126 <= tmp_217;
        end else if (((trunc_ln63_reg_594 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            local_aug_47_fu_126 <= select_ln64_1_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln63_reg_594 <= trunc_ln63_fu_294_p1;
    end
end

always @ (*) begin
    if (((icmp_ln63_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_c_1 = c_fu_94;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln63_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_aug_40_out_ap_vld = 1'b1;
    end else begin
        local_aug_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln63_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_aug_41_out_ap_vld = 1'b1;
    end else begin
        local_aug_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln63_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_aug_42_out_ap_vld = 1'b1;
    end else begin
        local_aug_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln63_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_aug_43_out_ap_vld = 1'b1;
    end else begin
        local_aug_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln63_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_aug_44_out_ap_vld = 1'b1;
    end else begin
        local_aug_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln63_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_aug_45_out_ap_vld = 1'b1;
    end else begin
        local_aug_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln63_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_aug_46_out_ap_vld = 1'b1;
    end else begin
        local_aug_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln63_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_aug_47_out_ap_vld = 1'b1;
    end else begin
        local_aug_47_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln63_fu_288_p2 = (ap_sig_allocacmp_c_1 + 4'd1);

assign and_ln64_fu_420_p2 = (xor_ln64_fu_414_p2 & tmp_229_fu_406_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln63_fu_282_p2 = ((ap_sig_allocacmp_c_1 == 4'd8) ? 1'b1 : 1'b0);

assign local_aug_40_out = local_aug_40_fu_98;

assign local_aug_41_out = local_aug_41_fu_102;

assign local_aug_42_out = local_aug_42_fu_106;

assign local_aug_43_out = local_aug_43_fu_110;

assign local_aug_44_out = local_aug_44_fu_114;

assign local_aug_45_out = local_aug_45_fu_118;

assign local_aug_46_out = local_aug_46_fu_122;

assign local_aug_47_out = local_aug_47_fu_126;

assign select_ln64_1_fu_440_p3 = ((xor_ln64_1_fu_426_p2[0:0] == 1'b1) ? select_ln64_fu_432_p3 : trunc_ln64_fu_402_p1);

assign select_ln64_fu_432_p3 = ((and_ln64_fu_420_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign sext_ln64_fu_384_p1 = $signed(tmp_s_fu_345_p19);

assign sub_ln64_fu_388_p2 = ($signed(17'd0) - $signed(sext_ln64_fu_384_p1));

assign tmp_229_fu_406_p3 = sub_ln64_fu_388_p2[32'd15];

assign tmp_fu_394_p3 = sub_ln64_fu_388_p2[32'd16];

assign tmp_s_fu_345_p17 = 'bx;

assign trunc_ln63_fu_294_p1 = ap_sig_allocacmp_c_1[2:0];

assign trunc_ln64_fu_402_p1 = sub_ln64_fu_388_p2[15:0];

assign xor_ln64_1_fu_426_p2 = (tmp_fu_394_p3 ^ tmp_229_fu_406_p3);

assign xor_ln64_fu_414_p2 = (tmp_fu_394_p3 ^ 1'd1);

endmodule //solve_top_decompose_qr_Pipeline_VITIS_LOOP_63_7
