// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_50_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        res_0,
        res_0_ap_vld,
        res_3,
        res_3_ap_vld,
        res_2,
        res_2_ap_vld,
        res_1,
        res_1_ap_vld,
        res_local_reload,
        res_local_1_reload,
        res_local_2_reload,
        res_local_3_reload
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] res_0;
output   res_0_ap_vld;
output  [15:0] res_3;
output   res_3_ap_vld;
output  [15:0] res_2;
output   res_2_ap_vld;
output  [15:0] res_1;
output   res_1_ap_vld;
input  [15:0] res_local_reload;
input  [15:0] res_local_1_reload;
input  [15:0] res_local_2_reload;
input  [15:0] res_local_3_reload;

reg ap_idle;
reg res_0_ap_vld;
reg res_3_ap_vld;
reg res_2_ap_vld;
reg res_1_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln50_fu_118_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] i_fu_54;
wire   [2:0] add_ln50_fu_124_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_3;
wire   [15:0] tmp_s_fu_134_p11;
wire   [1:0] trunc_ln50_fu_130_p1;
wire   [15:0] tmp_s_fu_134_p9;
wire   [1:0] tmp_s_fu_134_p10;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_s_fu_134_p1;
wire   [1:0] tmp_s_fu_134_p3;
wire  signed [1:0] tmp_s_fu_134_p5;
wire  signed [1:0] tmp_s_fu_134_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_54 = 3'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U399(
    .din0(res_local_reload),
    .din1(res_local_1_reload),
    .din2(res_local_2_reload),
    .din3(res_local_3_reload),
    .def(tmp_s_fu_134_p9),
    .sel(tmp_s_fu_134_p10),
    .dout(tmp_s_fu_134_p11)
);

solve_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln50_fu_118_p2 == 1'd0)) begin
            i_fu_54 <= add_ln50_fu_124_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_54 <= 3'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_118_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_3 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_54;
    end
end

always @ (*) begin
    if (((trunc_ln50_fu_130_p1 == 2'd0) & (icmp_ln50_fu_118_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        res_0_ap_vld = 1'b1;
    end else begin
        res_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_fu_130_p1 == 2'd1) & (icmp_ln50_fu_118_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        res_1_ap_vld = 1'b1;
    end else begin
        res_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_fu_130_p1 == 2'd2) & (icmp_ln50_fu_118_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        res_2_ap_vld = 1'b1;
    end else begin
        res_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_fu_130_p1 == 2'd3) & (icmp_ln50_fu_118_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        res_3_ap_vld = 1'b1;
    end else begin
        res_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln50_fu_124_p2 = (ap_sig_allocacmp_i_3 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln50_fu_118_p2 = ((ap_sig_allocacmp_i_3 == 3'd4) ? 1'b1 : 1'b0);

assign res_0 = tmp_s_fu_134_p11;

assign res_1 = tmp_s_fu_134_p11;

assign res_2 = tmp_s_fu_134_p11;

assign res_3 = tmp_s_fu_134_p11;

assign tmp_s_fu_134_p10 = ap_sig_allocacmp_i_3[1:0];

assign tmp_s_fu_134_p9 = 'bx;

assign trunc_ln50_fu_130_p1 = ap_sig_allocacmp_i_3[1:0];

endmodule //solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_50_7
