// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module solve_top_mat_vec_mul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        vec_0_val,
        vec_1_val,
        vec_2_val,
        vec_3_val,
        res_0,
        res_0_ap_vld,
        res_1,
        res_1_ap_vld,
        res_2,
        res_2_ap_vld,
        res_3,
        res_3_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
input  [15:0] vec_0_val;
input  [15:0] vec_1_val;
input  [15:0] vec_2_val;
input  [15:0] vec_3_val;
output  [15:0] res_0;
output   res_0_ap_vld;
output  [15:0] res_1;
output   res_1_ap_vld;
output  [15:0] res_2;
output   res_2_ap_vld;
output  [15:0] res_3;
output   res_3_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] res_0;
reg[15:0] res_1;
reg[15:0] res_2;
reg[15:0] res_3;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_done;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_idle;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_ready;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out_ap_vld;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_done;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_idle;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_ready;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3_ap_vld;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_idle;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_ready;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out_ap_vld;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_idle;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_ready;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld;
wire   [15:0] grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1;
wire    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld;
reg    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg;
reg    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [15:0] res_0_reg;
wire    ap_CS_fsm_state6;
reg   [15:0] res_3_reg;
reg   [15:0] res_2_reg;
reg   [15:0] res_1_reg;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg = 1'b0;
#0 grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg = 1'b0;
#0 grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg = 1'b0;
#0 grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg = 1'b0;
end

solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_24_1 grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start),
    .ap_done(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_done),
    .ap_idle(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_idle),
    .ap_ready(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_ready),
    .p_read(p_read),
    .p_read1(p_read1),
    .p_read2(p_read2),
    .p_read3(p_read3),
    .p_read4(p_read4),
    .p_read5(p_read5),
    .p_read6(p_read6),
    .p_read7(p_read7),
    .p_read8(p_read8),
    .p_read9(p_read9),
    .p_read10(p_read10),
    .p_read11(p_read11),
    .p_read12(p_read12),
    .p_read13(p_read13),
    .p_read14(p_read14),
    .p_read15(p_read15),
    .mat_local_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out),
    .mat_local_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out_ap_vld),
    .mat_local_1_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out),
    .mat_local_1_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out_ap_vld),
    .mat_local_2_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out),
    .mat_local_2_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out_ap_vld),
    .mat_local_3_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out),
    .mat_local_3_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out_ap_vld),
    .mat_local_4_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out),
    .mat_local_4_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out_ap_vld),
    .mat_local_5_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out),
    .mat_local_5_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out_ap_vld),
    .mat_local_6_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out),
    .mat_local_6_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out_ap_vld),
    .mat_local_7_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out),
    .mat_local_7_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out_ap_vld),
    .mat_local_8_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out),
    .mat_local_8_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out_ap_vld),
    .mat_local_9_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out),
    .mat_local_9_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out_ap_vld),
    .mat_local_10_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out),
    .mat_local_10_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out_ap_vld),
    .mat_local_11_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out),
    .mat_local_11_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out_ap_vld),
    .mat_local_12_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out),
    .mat_local_12_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out_ap_vld),
    .mat_local_13_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out),
    .mat_local_13_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out_ap_vld),
    .mat_local_14_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out),
    .mat_local_14_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out_ap_vld),
    .mat_local_15_load_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out),
    .mat_local_15_load_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out_ap_vld)
);

solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_29_3 grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start),
    .ap_done(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_done),
    .ap_idle(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_idle),
    .ap_ready(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_ready),
    .vec_0_val(vec_0_val),
    .vec_1_val(vec_1_val),
    .vec_2_val(vec_2_val),
    .vec_3_val(vec_3_val),
    .p_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out),
    .p_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out_ap_vld),
    .p_out1(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1),
    .p_out1_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1_ap_vld),
    .p_out2(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2),
    .p_out2_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2_ap_vld),
    .p_out3(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3),
    .p_out3_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3_ap_vld)
);

solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_40_5 grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start),
    .ap_done(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done),
    .ap_idle(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_idle),
    .ap_ready(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_ready),
    .mat_local_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out),
    .mat_local_1_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out),
    .mat_local_2_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out),
    .mat_local_3_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out),
    .conv7_i(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3),
    .mat_local_4_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out),
    .mat_local_5_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out),
    .mat_local_6_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out),
    .mat_local_7_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out),
    .conv7_i_1(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2),
    .mat_local_8_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out),
    .mat_local_9_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out),
    .mat_local_10_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out),
    .mat_local_11_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out),
    .conv7_i_2(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1),
    .mat_local_12_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out),
    .mat_local_13_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out),
    .mat_local_14_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out),
    .mat_local_15_load_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out),
    .conv7_i_3(grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out),
    .res_local_3_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out),
    .res_local_3_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out_ap_vld),
    .res_local_2_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out),
    .res_local_2_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out_ap_vld),
    .res_local_1_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out),
    .res_local_1_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out_ap_vld),
    .res_local_out(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out),
    .res_local_out_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out_ap_vld)
);

solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_50_7 grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start),
    .ap_done(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done),
    .ap_idle(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_idle),
    .ap_ready(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_ready),
    .res_0(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0),
    .res_0_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld),
    .res_3(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3),
    .res_3_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld),
    .res_2(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2),
    .res_2_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld),
    .res_1(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1),
    .res_1_ap_vld(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld),
    .res_local_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out),
    .res_local_1_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out),
    .res_local_2_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out),
    .res_local_3_reload(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg <= 1'b1;
        end else if ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_ready == 1'b1)) begin
            grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg <= 1'b1;
        end else if ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_ready == 1'b1)) begin
            grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg <= 1'b1;
        end else if ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_ready == 1'b1)) begin
            grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg <= 1'b1;
        end else if ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_ready == 1'b1)) begin
            grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_0_reg <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_1_reg <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_2_reg <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_3_reg <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_0 = grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0;
    end else begin
        res_0 = res_0_reg;
    end
end

always @ (*) begin
    if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_1 = grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1;
    end else begin
        res_1 = res_1_reg;
    end
end

always @ (*) begin
    if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_2 = grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2;
    end else begin
        res_2 = res_2_reg;
    end
end

always @ (*) begin
    if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_3 = grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3;
    end else begin
        res_3 = res_3_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_done == 1'b0) | (grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_done == 1'b0));
end

assign grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start = grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg;

assign grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start = grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg;

assign grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start = grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg;

assign grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start = grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg;

assign res_0_ap_vld = grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld;

assign res_1_ap_vld = grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld;

assign res_2_ap_vld = grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld;

assign res_3_ap_vld = grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld;

endmodule //solve_top_mat_vec_mul
