-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity solve_top_cordic_atan is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_0_0_035226 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_0_0_035325 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of solve_top_cordic_atan is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv16_E6DE : STD_LOGIC_VECTOR (15 downto 0) := "1110011011011110";
    constant ap_const_lv16_1922 : STD_LOGIC_VECTOR (15 downto 0) := "0001100100100010";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal atan_table_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal atan_table_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_639_reg_1033 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_shift_fu_411_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_shift_reg_1040 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_shift_fu_417_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_shift_reg_1045 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_640_reg_1055 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal x_temp_reg_1062 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_641_reg_1067 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_642_reg_1072 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_644_reg_1078 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_temp_reg_1085 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_645_reg_1090 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_646_reg_1095 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_648_reg_1101 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_reg_1108 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_649_reg_1113 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_650_reg_1118 : STD_LOGIC_VECTOR (0 downto 0);
    signal theta_out_write_assign_reg_125 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln70_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln81_fu_394_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_25_fu_84 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal x_temp_102_fu_755_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_26_fu_342_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal y_25_fu_88 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y_temp_102_fu_860_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_26_fu_334_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_fu_92 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln81_fu_382_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal z_fu_96 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal z_26_fu_965_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal z_29_ph_fu_326_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal atan_table_ce0_local : STD_LOGIC;
    signal or_ln70_fu_136_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln70_fu_136_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln70_fu_136_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_148_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln77_fu_156_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln77_fu_156_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln77_fu_160_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_634_fu_166_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_635_fu_178_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln77_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln77_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln77_1_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln77_fu_204_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln77_fu_174_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln77_1_fu_220_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln77_1_fu_220_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln77_1_fu_224_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_636_fu_230_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_637_fu_242_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln77_2_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln77_1_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln77_3_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln77_2_fu_268_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln77_1_fu_238_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_fu_276_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_148_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln76_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_298_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_638_fu_284_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_58_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln78_1_cast_fu_312_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_26_fu_334_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_fu_212_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_26_fu_342_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln84_fu_407_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln86_1_fu_428_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sub_ln86_1_fu_435_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln86_fu_441_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln_fu_452_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln86_1_fu_459_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln86_fu_448_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln86_fu_463_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal shl_ln87_1_fu_503_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln87_fu_510_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln87_fu_514_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal shl_ln3_fu_527_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln87_1_fu_534_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln87_fu_520_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln87_fu_538_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal shl_ln88_1_fu_578_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln88_1_fu_586_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln88_1_fu_590_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal shl_ln4_fu_603_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln88_fu_596_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln88_fu_610_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln88_1_fu_614_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln88_fu_618_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln86_fu_658_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_temp_100_fu_661_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_643_fu_666_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_2_fu_685_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln86_2_fu_690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_4_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_3_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln86_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_1_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln86_3_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_5_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_1_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_2_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln86_1_fu_749_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_1_fu_741_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln87_fu_763_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_temp_100_fu_766_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_647_fu_771_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln87_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln87_2_fu_790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln87_2_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln87_4_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln87_3_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln87_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln87_1_fu_806_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln87_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln87_3_fu_829_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln87_5_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln87_1_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln87_2_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln87_1_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln87_1_fu_846_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln88_fu_868_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln88_fu_871_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_651_fu_876_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln88_fu_884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln88_2_fu_895_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln88_2_fu_900_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln88_4_fu_906_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln88_3_fu_916_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln88_fu_922_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln88_1_fu_911_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln88_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln88_3_fu_934_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln88_5_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln88_1_fu_928_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln88_2_fu_946_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln88_1_fu_959_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln88_1_fu_951_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component solve_top_cordic_atan_atan_table_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    atan_table_U : component solve_top_cordic_atan_atan_table_ROM_AUTO_1R
    generic map (
        DataWidth => 11,
        AddressRange => 13,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => atan_table_address0,
        ce0 => atan_table_ce0_local,
        q0 => atan_table_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv16_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    ap_return_preg <= theta_out_write_assign_reg_125;
                end if; 
            end if;
        end if;
    end process;


    i_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln70_fu_142_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_92 <= ap_const_lv4_0;
            elsif (((icmp_ln81_fu_376_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_fu_92 <= add_ln81_fu_382_p2;
            end if; 
        end if;
    end process;

    theta_out_write_assign_reg_125_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln81_fu_376_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                theta_out_write_assign_reg_125 <= z_fu_96;
            elsif (((icmp_ln70_fu_142_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                theta_out_write_assign_reg_125 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    x_25_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln70_fu_142_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                x_25_fu_84 <= x_26_fu_342_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                x_25_fu_84 <= x_temp_102_fu_755_p3;
            end if; 
        end if;
    end process;

    y_25_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln70_fu_142_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                y_25_fu_88 <= y_26_fu_334_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                y_25_fu_88 <= y_temp_102_fu_860_p3;
            end if; 
        end if;
    end process;

    z_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln70_fu_142_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                z_fu_96 <= z_29_ph_fu_326_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                z_fu_96 <= z_26_fu_965_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_639_reg_1033 <= y_25_fu_88(15 downto 15);
                x_shift_reg_1040 <= x_shift_fu_411_p2;
                y_shift_reg_1045 <= y_shift_fu_417_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                tmp_640_reg_1055 <= sub_ln86_fu_463_p2(27 downto 27);
                tmp_641_reg_1067 <= sub_ln86_fu_463_p2(10 downto 10);
                tmp_642_reg_1072 <= sub_ln86_fu_463_p2(26 downto 26);
                tmp_644_reg_1078 <= add_ln87_fu_538_p2(27 downto 27);
                tmp_645_reg_1090 <= select_ln87_fu_520_p3(10 downto 10);
                tmp_646_reg_1095 <= add_ln87_fu_538_p2(26 downto 26);
                tmp_648_reg_1101 <= sub_ln88_fu_618_p2(27 downto 27);
                tmp_649_reg_1113 <= sub_ln88_fu_618_p2(10 downto 10);
                tmp_650_reg_1118 <= sub_ln88_fu_618_p2(26 downto 26);
                trunc_ln_reg_1108 <= sub_ln88_fu_618_p2(26 downto 11);
                x_temp_reg_1062 <= sub_ln86_fu_463_p2(26 downto 11);
                y_temp_reg_1085 <= add_ln87_fu_538_p2(26 downto 11);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln70_fu_142_p2, icmp_ln81_fu_376_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln70_fu_142_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((icmp_ln70_fu_142_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln81_fu_376_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln81_fu_382_p2 <= std_logic_vector(unsigned(i_fu_92) + unsigned(ap_const_lv4_1));
    add_ln87_fu_538_p2 <= std_logic_vector(signed(sext_ln87_1_fu_534_p1) + signed(select_ln87_fu_520_p3));
    add_ln88_fu_871_p2 <= std_logic_vector(unsigned(trunc_ln_reg_1108) + unsigned(zext_ln88_fu_868_p1));
    and_ln77_1_fu_256_p2 <= (xor_ln77_2_fu_250_p2 and tmp_637_fu_242_p3);
    and_ln77_fu_192_p2 <= (xor_ln77_fu_186_p2 and tmp_635_fu_178_p3);
    and_ln86_1_fu_718_p2 <= (xor_ln86_1_fu_701_p2 and or_ln86_fu_712_p2);
    and_ln86_2_fu_736_p2 <= (xor_ln86_5_fu_730_p2 and tmp_640_reg_1055);
    and_ln86_fu_680_p2 <= (xor_ln86_fu_674_p2 and tmp_642_reg_1072);
    and_ln87_1_fu_823_p2 <= (xor_ln87_1_fu_806_p2 and or_ln87_fu_817_p2);
    and_ln87_2_fu_841_p2 <= (xor_ln87_5_fu_835_p2 and tmp_644_reg_1078);
    and_ln87_fu_785_p2 <= (xor_ln87_fu_779_p2 and tmp_646_reg_1095);
    and_ln88_1_fu_928_p2 <= (xor_ln88_1_fu_911_p2 and or_ln88_fu_922_p2);
    and_ln88_2_fu_946_p2 <= (xor_ln88_5_fu_940_p2 and tmp_648_reg_1101);
    and_ln88_fu_890_p2 <= (xor_ln88_fu_884_p2 and tmp_650_reg_1118);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(theta_out_write_assign_reg_125, ap_return_preg, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_return <= theta_out_write_assign_reg_125;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    atan_table_address0 <= zext_ln81_fu_394_p1(4 - 1 downto 0);

    atan_table_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            atan_table_ce0_local <= ap_const_logic_1;
        else 
            atan_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_58_fu_320_p2 <= (tmp_638_fu_284_p3 or empty_fu_306_p2);
    empty_fu_306_p2 <= "1" when (sel_tmp2_fu_298_p3 = ap_const_lv2_2) else "0";
    icmp_ln70_fu_142_p2 <= "1" when (or_ln70_fu_136_p2 = ap_const_lv16_0) else "0";
    icmp_ln81_fu_376_p2 <= "1" when (i_fu_92 = ap_const_lv4_D) else "0";
    or_ln70_fu_136_p0 <= p_0_0_035325;
    or_ln70_fu_136_p1 <= p_0_0_035226;
    or_ln70_fu_136_p2 <= (or_ln70_fu_136_p1 or or_ln70_fu_136_p0);
    or_ln86_1_fu_749_p2 <= (and_ln86_2_fu_736_p2 or and_ln86_1_fu_718_p2);
    or_ln86_2_fu_690_p2 <= (xor_ln86_2_fu_685_p2 or tmp_643_fu_666_p3);
    or_ln86_3_fu_724_p2 <= (tmp_643_fu_666_p3 or and_ln86_fu_680_p2);
    or_ln86_fu_712_p2 <= (xor_ln86_3_fu_706_p2 or tmp_643_fu_666_p3);
    or_ln87_1_fu_854_p2 <= (and_ln87_2_fu_841_p2 or and_ln87_1_fu_823_p2);
    or_ln87_2_fu_795_p2 <= (xor_ln87_2_fu_790_p2 or tmp_647_fu_771_p3);
    or_ln87_3_fu_829_p2 <= (tmp_647_fu_771_p3 or and_ln87_fu_785_p2);
    or_ln87_fu_817_p2 <= (xor_ln87_3_fu_811_p2 or tmp_647_fu_771_p3);
    or_ln88_1_fu_959_p2 <= (and_ln88_2_fu_946_p2 or and_ln88_1_fu_928_p2);
    or_ln88_2_fu_900_p2 <= (xor_ln88_2_fu_895_p2 or tmp_651_fu_876_p3);
    or_ln88_3_fu_934_p2 <= (tmp_651_fu_876_p3 or and_ln88_fu_890_p2);
    or_ln88_fu_922_p2 <= (xor_ln88_3_fu_916_p2 or tmp_651_fu_876_p3);
    sel_tmp2_fu_298_p3 <= (xor_ln76_fu_292_p2 & ap_const_lv1_0);
    select_ln77_2_fu_268_p3 <= 
        ap_const_lv16_7FFF when (and_ln77_1_fu_256_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln77_fu_204_p3 <= 
        ap_const_lv16_7FFF when (and_ln77_fu_192_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln78_1_cast_fu_312_p3 <= 
        ap_const_lv16_0 when (empty_fu_306_p2(0) = '1') else 
        ap_const_lv16_E6DE;
    select_ln86_1_fu_741_p3 <= 
        ap_const_lv16_7FFF when (and_ln86_1_fu_718_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln86_fu_441_p3 <= 
        shl_ln86_1_fu_428_p3 when (tmp_639_reg_1033(0) = '1') else 
        sub_ln86_1_fu_435_p2;
    select_ln87_1_fu_846_p3 <= 
        ap_const_lv16_7FFF when (and_ln87_1_fu_823_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln87_fu_520_p3 <= 
        sext_ln87_fu_510_p1 when (tmp_639_reg_1033(0) = '1') else 
        sub_ln87_fu_514_p2;
    select_ln88_1_fu_951_p3 <= 
        ap_const_lv16_7FFF when (and_ln88_1_fu_928_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln88_fu_596_p3 <= 
        zext_ln88_1_fu_586_p1 when (tmp_639_reg_1033(0) = '1') else 
        sub_ln88_1_fu_590_p2;
    sext_ln77_1_fu_220_p0 <= p_0_0_035325;
        sext_ln77_1_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln77_1_fu_220_p0),17));

    sext_ln77_fu_156_p0 <= p_0_0_035226;
        sext_ln77_fu_156_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln77_fu_156_p0),17));

        sext_ln86_1_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_452_p3),28));

        sext_ln86_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln86_fu_441_p3),28));

        sext_ln87_1_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln3_fu_527_p3),28));

        sext_ln87_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln87_1_fu_503_p3),28));

        sext_ln88_1_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln88_fu_596_p3),28));

        sext_ln88_fu_610_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln4_fu_603_p3),28));

    shl_ln3_fu_527_p3 <= (y_25_fu_88 & ap_const_lv11_0);
    shl_ln4_fu_603_p3 <= (z_fu_96 & ap_const_lv11_0);
    shl_ln86_1_fu_428_p3 <= (y_shift_reg_1045 & ap_const_lv11_0);
    shl_ln87_1_fu_503_p3 <= (x_shift_reg_1040 & ap_const_lv11_0);
    shl_ln88_1_fu_578_p3 <= (atan_table_q0 & ap_const_lv11_0);
    shl_ln_fu_452_p3 <= (x_25_fu_84 & ap_const_lv11_0);
    sub_ln77_1_fu_224_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln77_1_fu_220_p1));
    sub_ln77_fu_160_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln77_fu_156_p1));
    sub_ln86_1_fu_435_p2 <= std_logic_vector(unsigned(ap_const_lv27_0) - unsigned(shl_ln86_1_fu_428_p3));
    sub_ln86_fu_463_p2 <= std_logic_vector(signed(sext_ln86_1_fu_459_p1) - signed(sext_ln86_fu_448_p1));
    sub_ln87_fu_514_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(sext_ln87_fu_510_p1));
    sub_ln88_1_fu_590_p2 <= std_logic_vector(unsigned(ap_const_lv23_0) - unsigned(zext_ln88_1_fu_586_p1));
    sub_ln88_fu_618_p2 <= std_logic_vector(signed(sext_ln88_fu_610_p1) - signed(sext_ln88_1_fu_614_p1));
    tmp_634_fu_166_p3 <= sub_ln77_fu_160_p2(16 downto 16);
    tmp_635_fu_178_p3 <= sub_ln77_fu_160_p2(15 downto 15);
    tmp_636_fu_230_p3 <= sub_ln77_1_fu_224_p2(16 downto 16);
    tmp_637_fu_242_p3 <= sub_ln77_1_fu_224_p2(15 downto 15);
    tmp_638_fu_284_p3 <= y_fu_276_p3(15 downto 15);
    tmp_643_fu_666_p3 <= x_temp_100_fu_661_p2(15 downto 15);
    tmp_647_fu_771_p3 <= y_temp_100_fu_766_p2(15 downto 15);
    tmp_651_fu_876_p3 <= add_ln88_fu_871_p2(15 downto 15);
    tmp_fu_148_p1 <= p_0_0_035226;
    tmp_fu_148_p3 <= tmp_fu_148_p1(15 downto 15);
    trunc_ln77_1_fu_238_p1 <= sub_ln77_1_fu_224_p2(16 - 1 downto 0);
    trunc_ln77_fu_174_p1 <= sub_ln77_fu_160_p2(16 - 1 downto 0);
    x_26_fu_342_p2 <= p_0_0_035226;
    x_26_fu_342_p3 <= 
        x_fu_212_p3 when (tmp_fu_148_p3(0) = '1') else 
        x_26_fu_342_p2;
    x_fu_212_p3 <= 
        select_ln77_fu_204_p3 when (xor_ln77_1_fu_198_p2(0) = '1') else 
        trunc_ln77_fu_174_p1;
    x_shift_fu_411_p2 <= std_logic_vector(shift_right(signed(x_25_fu_84),to_integer(unsigned('0' & zext_ln84_fu_407_p1(16-1 downto 0)))));
    x_temp_100_fu_661_p2 <= std_logic_vector(unsigned(x_temp_reg_1062) + unsigned(zext_ln86_fu_658_p1));
    x_temp_102_fu_755_p3 <= 
        select_ln86_1_fu_741_p3 when (or_ln86_1_fu_749_p2(0) = '1') else 
        x_temp_100_fu_661_p2;
    xor_ln76_fu_292_p2 <= (tmp_fu_148_p3 xor ap_const_lv1_1);
    xor_ln77_1_fu_198_p2 <= (tmp_635_fu_178_p3 xor tmp_634_fu_166_p3);
    xor_ln77_2_fu_250_p2 <= (tmp_636_fu_230_p3 xor ap_const_lv1_1);
    xor_ln77_3_fu_262_p2 <= (tmp_637_fu_242_p3 xor tmp_636_fu_230_p3);
    xor_ln77_fu_186_p2 <= (tmp_634_fu_166_p3 xor ap_const_lv1_1);
    xor_ln86_1_fu_701_p2 <= (tmp_640_reg_1055 xor ap_const_lv1_1);
    xor_ln86_2_fu_685_p2 <= (tmp_642_reg_1072 xor ap_const_lv1_1);
    xor_ln86_3_fu_706_p2 <= (xor_ln86_4_fu_696_p2 xor ap_const_lv1_1);
    xor_ln86_4_fu_696_p2 <= (tmp_640_reg_1055 xor or_ln86_2_fu_690_p2);
    xor_ln86_5_fu_730_p2 <= (or_ln86_3_fu_724_p2 xor ap_const_lv1_1);
    xor_ln86_fu_674_p2 <= (tmp_643_fu_666_p3 xor ap_const_lv1_1);
    xor_ln87_1_fu_806_p2 <= (tmp_644_reg_1078 xor ap_const_lv1_1);
    xor_ln87_2_fu_790_p2 <= (tmp_646_reg_1095 xor ap_const_lv1_1);
    xor_ln87_3_fu_811_p2 <= (xor_ln87_4_fu_801_p2 xor ap_const_lv1_1);
    xor_ln87_4_fu_801_p2 <= (tmp_644_reg_1078 xor or_ln87_2_fu_795_p2);
    xor_ln87_5_fu_835_p2 <= (or_ln87_3_fu_829_p2 xor ap_const_lv1_1);
    xor_ln87_fu_779_p2 <= (tmp_647_fu_771_p3 xor ap_const_lv1_1);
    xor_ln88_1_fu_911_p2 <= (tmp_648_reg_1101 xor ap_const_lv1_1);
    xor_ln88_2_fu_895_p2 <= (tmp_650_reg_1118 xor ap_const_lv1_1);
    xor_ln88_3_fu_916_p2 <= (xor_ln88_4_fu_906_p2 xor ap_const_lv1_1);
    xor_ln88_4_fu_906_p2 <= (tmp_648_reg_1101 xor or_ln88_2_fu_900_p2);
    xor_ln88_5_fu_940_p2 <= (or_ln88_3_fu_934_p2 xor ap_const_lv1_1);
    xor_ln88_fu_884_p2 <= (tmp_651_fu_876_p3 xor ap_const_lv1_1);
    y_26_fu_334_p2 <= p_0_0_035325;
    y_26_fu_334_p3 <= 
        y_fu_276_p3 when (tmp_fu_148_p3(0) = '1') else 
        y_26_fu_334_p2;
    y_fu_276_p3 <= 
        select_ln77_2_fu_268_p3 when (xor_ln77_3_fu_262_p2(0) = '1') else 
        trunc_ln77_1_fu_238_p1;
    y_shift_fu_417_p2 <= std_logic_vector(shift_right(signed(y_25_fu_88),to_integer(unsigned('0' & zext_ln84_fu_407_p1(16-1 downto 0)))));
    y_temp_100_fu_766_p2 <= std_logic_vector(unsigned(y_temp_reg_1085) + unsigned(zext_ln87_fu_763_p1));
    y_temp_102_fu_860_p3 <= 
        select_ln87_1_fu_846_p3 when (or_ln87_1_fu_854_p2(0) = '1') else 
        y_temp_100_fu_766_p2;
    z_26_fu_965_p3 <= 
        select_ln88_1_fu_951_p3 when (or_ln88_1_fu_959_p2(0) = '1') else 
        add_ln88_fu_871_p2;
    z_29_ph_fu_326_p3 <= 
        select_ln78_1_cast_fu_312_p3 when (empty_58_fu_320_p2(0) = '1') else 
        ap_const_lv16_1922;
    zext_ln81_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_92),64));
    zext_ln84_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_92),16));
    zext_ln86_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_641_reg_1067),16));
    zext_ln87_fu_763_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_645_reg_1090),16));
    zext_ln88_1_fu_586_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln88_1_fu_578_p3),23));
    zext_ln88_fu_868_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_649_reg_1113),16));
end behav;
