-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity solve_top_upper_backsub is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
    y_in_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    y_in_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    y_in_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    y_in_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    x_out_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    x_out_0_ap_vld : OUT STD_LOGIC;
    x_out_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    x_out_1_ap_vld : OUT STD_LOGIC;
    x_out_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    x_out_2_ap_vld : OUT STD_LOGIC;
    x_out_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    x_out_3_ap_vld : OUT STD_LOGIC );
end;


architecture behav of solve_top_upper_backsub is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (41 downto 0) := "000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (41 downto 0) := "000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (41 downto 0) := "000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (41 downto 0) := "000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (41 downto 0) := "000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (41 downto 0) := "000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (41 downto 0) := "000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (41 downto 0) := "000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (41 downto 0) := "000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (41 downto 0) := "001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (41 downto 0) := "010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (41 downto 0) := "100000000000000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_507 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_1_fu_615_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal reg_512 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_517 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln33_fu_623_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln33_fu_627_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln33_reg_1557 : STD_LOGIC_VECTOR (1 downto 0);
    signal acc_fu_631_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_651_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_1568 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_671_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_reg_1573 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_691_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_reg_1579 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_711_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_reg_1585 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln35_fu_790_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln35_reg_1609 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln40_fu_815_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_reg_1614 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal add_ln37_fu_889_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln37_reg_1633 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal and_ln37_3_fu_1010_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln37_3_reg_1638 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln37_1_fu_1040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln37_1_reg_1643 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_2_fu_1053_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal select_ln43_1_fu_1151_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln43_1_reg_1653 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state40 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state40 : signal is "none";
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_start : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_done : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_idle : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_ready : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_3_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_3_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_2_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_2_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_1_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_1_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_1_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_2_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_2_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_3_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_3_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_4_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_4_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_5_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_5_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_6_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_6_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_7_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_7_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_8_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_8_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_9_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_9_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_10_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_10_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_11_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_11_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_12_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_12_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_13_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_13_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_14_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_14_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_15_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_15_load_out_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_start : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_idle : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_ready : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2_ap_vld : STD_LOGIC;
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1_ap_vld : STD_LOGIC;
    signal j_reg_382 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_1_reg_391 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_xloc_4_phi_fu_405_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal xloc_4_reg_401 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state41 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state41 : signal is "none";
    signal icmp_ln35_fu_735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_start_reg : STD_LOGIC := '0';
    signal x_out_0_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state42 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state42 : signal is "none";
    signal x_out_3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_out_2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_out_1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal indvars_iv27_fu_158 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln33_1_fu_1193_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_1_fu_162 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln33_fu_1188_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal xloc_fu_246 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal xloc_1_fu_250 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal xloc_2_fu_254 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal xloc_3_fu_258 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_fu_631_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_651_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_671_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_691_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_711_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_745_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln35_fu_741_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_745_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_766_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_766_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal diag_fu_796_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal diag_fu_796_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1_fu_821_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_fu_837_p0 : STD_LOGIC_VECTOR (27 downto 0);
    signal shl_ln_fu_843_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_fu_1209_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_871_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln3_fu_862_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln37_fu_885_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_895_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_878_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_fu_903_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_922_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_937_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln37_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_1_fu_946_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_2_fu_952_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_915_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_1_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln37_1_fu_972_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln37_fu_958_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_2_fu_992_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_855_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln37_fu_998_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_3_fu_1004_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln37_1_fu_978_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln37_2_fu_986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln37_4_fu_1016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln37_2_fu_1022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_4_fu_1028_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln37_5_fu_1034_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln37_2_fu_1046_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_837_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_15_fu_1079_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_14_fu_1071_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_1_fu_1095_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_1059_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_fu_1101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln43_fu_1107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_fu_1089_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln43_1_fu_1119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_1_fu_1125_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_fu_1113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_1_fu_1131_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_2_fu_1145_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_fu_1137_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln43_fu_1067_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_837_ap_start : STD_LOGIC;
    signal grp_fu_837_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (41 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ST_fsm_state36_blk : STD_LOGIC;
    signal ap_ST_fsm_state37_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_ST_fsm_state39_blk : STD_LOGIC;
    signal ap_ST_fsm_state40_blk : STD_LOGIC;
    signal ap_ST_fsm_state41_blk : STD_LOGIC;
    signal ap_ST_fsm_state42_blk : STD_LOGIC;
    signal acc_fu_631_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal acc_fu_631_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal acc_fu_631_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal acc_fu_631_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_651_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_651_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_651_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_651_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_671_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_671_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_671_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_671_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_691_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_691_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_691_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_691_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_711_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_711_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_711_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_711_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_745_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_745_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_745_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_766_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_766_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_766_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal diag_fu_796_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal diag_fu_796_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal diag_fu_796_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal diag_fu_796_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component solve_top_upper_backsub_Pipeline_VITIS_LOOP_20_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y_in_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
        y_in_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
        y_in_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
        y_in_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
        yloc_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        yloc_3_out_ap_vld : OUT STD_LOGIC;
        yloc_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        yloc_2_out_ap_vld : OUT STD_LOGIC;
        yloc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        yloc_1_out_ap_vld : OUT STD_LOGIC;
        yloc_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        yloc_out_ap_vld : OUT STD_LOGIC;
        Rloc_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_1_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_1_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_2_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_2_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_3_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_3_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_4_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_4_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_5_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_5_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_6_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_6_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_7_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_7_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_8_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_8_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_9_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_9_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_10_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_10_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_11_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_11_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_12_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_12_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_13_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_13_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_14_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_14_load_out_ap_vld : OUT STD_LOGIC;
        Rloc_15_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Rloc_15_load_out_ap_vld : OUT STD_LOGIC );
    end component;


    component solve_top_upper_backsub_Pipeline_VITIS_LOOP_48_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_out_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        x_out_0_ap_vld : OUT STD_LOGIC;
        x_out_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        x_out_3_ap_vld : OUT STD_LOGIC;
        x_out_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        x_out_2_ap_vld : OUT STD_LOGIC;
        x_out_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        x_out_1_ap_vld : OUT STD_LOGIC;
        xloc_load : IN STD_LOGIC_VECTOR (15 downto 0);
        xloc_1_load_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        xloc_2_load_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        xloc_3_load_1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component solve_top_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component solve_top_sparsemux_7_2_16_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component solve_top_sdiv_28s_16s_28_32_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component solve_top_mac_mulsub_16s_16s_27s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (26 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412 : component solve_top_upper_backsub_Pipeline_VITIS_LOOP_20_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_start,
        ap_done => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_done,
        ap_idle => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_idle,
        ap_ready => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_ready,
        y_in_0_val => y_in_0_val,
        y_in_1_val => y_in_1_val,
        y_in_2_val => y_in_2_val,
        y_in_3_val => y_in_3_val,
        p_read => p_read,
        p_read1 => p_read1,
        p_read2 => p_read2,
        p_read3 => p_read3,
        p_read4 => p_read4,
        p_read5 => p_read5,
        p_read6 => p_read6,
        p_read7 => p_read7,
        p_read8 => p_read8,
        p_read9 => p_read9,
        p_read10 => p_read10,
        p_read11 => p_read11,
        p_read12 => p_read12,
        p_read13 => p_read13,
        p_read14 => p_read14,
        p_read15 => p_read15,
        yloc_3_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_3_out,
        yloc_3_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_3_out_ap_vld,
        yloc_2_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_2_out,
        yloc_2_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_2_out_ap_vld,
        yloc_1_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_1_out,
        yloc_1_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_1_out_ap_vld,
        yloc_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_out,
        yloc_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_out_ap_vld,
        Rloc_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_load_out,
        Rloc_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_load_out_ap_vld,
        Rloc_1_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_1_load_out,
        Rloc_1_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_1_load_out_ap_vld,
        Rloc_2_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_2_load_out,
        Rloc_2_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_2_load_out_ap_vld,
        Rloc_3_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_3_load_out,
        Rloc_3_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_3_load_out_ap_vld,
        Rloc_4_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_4_load_out,
        Rloc_4_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_4_load_out_ap_vld,
        Rloc_5_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_5_load_out,
        Rloc_5_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_5_load_out_ap_vld,
        Rloc_6_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_6_load_out,
        Rloc_6_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_6_load_out_ap_vld,
        Rloc_7_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_7_load_out,
        Rloc_7_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_7_load_out_ap_vld,
        Rloc_8_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_8_load_out,
        Rloc_8_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_8_load_out_ap_vld,
        Rloc_9_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_9_load_out,
        Rloc_9_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_9_load_out_ap_vld,
        Rloc_10_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_10_load_out,
        Rloc_10_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_10_load_out_ap_vld,
        Rloc_11_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_11_load_out,
        Rloc_11_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_11_load_out_ap_vld,
        Rloc_12_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_12_load_out,
        Rloc_12_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_12_load_out_ap_vld,
        Rloc_13_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_13_load_out,
        Rloc_13_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_13_load_out_ap_vld,
        Rloc_14_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_14_load_out,
        Rloc_14_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_14_load_out_ap_vld,
        Rloc_15_load_out => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_15_load_out,
        Rloc_15_load_out_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_15_load_out_ap_vld);

    grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476 : component solve_top_upper_backsub_Pipeline_VITIS_LOOP_48_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_start,
        ap_done => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done,
        ap_idle => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_idle,
        ap_ready => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_ready,
        x_out_0 => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0,
        x_out_0_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0_ap_vld,
        x_out_3 => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3,
        x_out_3_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3_ap_vld,
        x_out_2 => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2,
        x_out_2_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2_ap_vld,
        x_out_1 => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1,
        x_out_1_ap_vld => grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1_ap_vld,
        xloc_load => xloc_fu_246,
        xloc_1_load_1 => reg_507,
        xloc_2_load_1 => reg_512,
        xloc_3_load_1 => reg_517);

    sparsemux_9_2_16_1_1_U486 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_out,
        din1 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_1_out,
        din2 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_2_out,
        din3 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_yloc_3_out,
        def => acc_fu_631_p9,
        sel => trunc_ln33_fu_627_p1,
        dout => acc_fu_631_p11);

    sparsemux_9_2_16_1_1_U487 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_load_out,
        din1 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_1_load_out,
        din2 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_2_load_out,
        din3 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_3_load_out,
        def => tmp_fu_651_p9,
        sel => trunc_ln33_fu_627_p1,
        dout => tmp_fu_651_p11);

    sparsemux_9_2_16_1_1_U488 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_4_load_out,
        din1 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_5_load_out,
        din2 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_6_load_out,
        din3 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_7_load_out,
        def => tmp_5_fu_671_p9,
        sel => trunc_ln33_fu_627_p1,
        dout => tmp_5_fu_671_p11);

    sparsemux_9_2_16_1_1_U489 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_8_load_out,
        din1 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_9_load_out,
        din2 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_10_load_out,
        din3 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_11_load_out,
        def => tmp_6_fu_691_p9,
        sel => trunc_ln33_fu_627_p1,
        dout => tmp_6_fu_691_p11);

    sparsemux_9_2_16_1_1_U490 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_12_load_out,
        din1 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_13_load_out,
        din2 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_14_load_out,
        din3 => grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_Rloc_15_load_out,
        def => tmp_7_fu_711_p9,
        sel => trunc_ln33_fu_627_p1,
        dout => tmp_7_fu_711_p11);

    sparsemux_7_2_16_1_1_x_U491 : component solve_top_sparsemux_7_2_16_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 16,
        CASE1 => "10",
        din1_WIDTH => 16,
        CASE2 => "11",
        din2_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => tmp_5_reg_1573,
        din1 => tmp_6_reg_1579,
        din2 => tmp_7_reg_1585,
        def => tmp_9_fu_745_p7,
        sel => trunc_ln35_fu_741_p1,
        dout => tmp_9_fu_745_p9);

    sparsemux_7_2_16_1_1_x_U492 : component solve_top_sparsemux_7_2_16_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 16,
        CASE1 => "10",
        din1_WIDTH => 16,
        CASE2 => "11",
        din2_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => reg_507,
        din1 => reg_512,
        din2 => reg_517,
        def => tmp_s_fu_766_p7,
        sel => trunc_ln35_fu_741_p1,
        dout => tmp_s_fu_766_p9);

    sparsemux_9_2_16_1_1_U493 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => tmp_reg_1568,
        din1 => tmp_5_reg_1573,
        din2 => tmp_6_reg_1579,
        din3 => tmp_7_reg_1585,
        def => diag_fu_796_p9,
        sel => trunc_ln33_reg_1557,
        dout => diag_fu_796_p11);

    sdiv_28s_16s_28_32_seq_1_U494 : component solve_top_sdiv_28s_16s_28_32_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 32,
        din0_WIDTH => 28,
        din1_WIDTH => 16,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_837_ap_start,
        done => grp_fu_837_ap_done,
        din0 => grp_fu_837_p0,
        din1 => diag_fu_796_p11,
        ce => ap_const_logic_1,
        dout => grp_fu_837_p2);

    mac_mulsub_16s_16s_27s_32_4_1_U495 : component solve_top_mac_mulsub_16s_16s_27s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 27,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_s_fu_766_p9,
        din1 => tmp_9_fu_745_p9,
        din2 => shl_ln_fu_843_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_1209_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_ready = ap_const_logic_1)) then 
                    grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_start_reg <= ap_const_logic_0;
            else
                if (((tmp_1_fu_615_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_ready = ap_const_logic_1)) then 
                    grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    acc_1_reg_391_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                acc_1_reg_391 <= acc_2_fu_1053_p3;
            elsif (((tmp_1_fu_615_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                acc_1_reg_391 <= acc_fu_631_p11;
            end if; 
        end if;
    end process;

    i_1_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_1_fu_162 <= ap_const_lv3_3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state41)) then 
                i_1_fu_162 <= add_ln33_fu_1188_p2;
            end if; 
        end if;
    end process;

    indvars_iv27_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvars_iv27_fu_158 <= ap_const_lv3_4;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state41)) then 
                indvars_iv27_fu_158 <= add_ln33_1_fu_1193_p2;
            end if; 
        end if;
    end process;

    j_reg_382_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                j_reg_382 <= add_ln35_reg_1609;
            elsif (((tmp_1_fu_615_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j_reg_382 <= zext_ln33_fu_623_p1;
            end if; 
        end if;
    end process;

    xloc_1_fu_250_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                xloc_1_fu_250 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state41) and (trunc_ln33_reg_1557 = ap_const_lv2_1))) then 
                xloc_1_fu_250 <= ap_phi_mux_xloc_4_phi_fu_405_p4;
            end if; 
        end if;
    end process;

    xloc_2_fu_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                xloc_2_fu_254 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state41) and (trunc_ln33_reg_1557 = ap_const_lv2_2))) then 
                xloc_2_fu_254 <= ap_phi_mux_xloc_4_phi_fu_405_p4;
            end if; 
        end if;
    end process;

    xloc_3_fu_258_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                xloc_3_fu_258 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state41) and (trunc_ln33_reg_1557 = ap_const_lv2_3))) then 
                xloc_3_fu_258 <= ap_phi_mux_xloc_4_phi_fu_405_p4;
            end if; 
        end if;
    end process;

    xloc_4_reg_401_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln35_fu_735_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln40_fu_815_p2 = ap_const_lv1_1))) then 
                xloc_4_reg_401 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state41) and (icmp_ln40_reg_1614 = ap_const_lv1_0))) then 
                xloc_4_reg_401 <= select_ln43_1_reg_1653;
            end if; 
        end if;
    end process;

    xloc_fu_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                xloc_fu_246 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state41) and (trunc_ln33_reg_1557 = ap_const_lv2_0))) then 
                xloc_fu_246 <= ap_phi_mux_xloc_4_phi_fu_405_p4;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln35_reg_1609 <= add_ln35_fu_790_p2;
                icmp_ln40_reg_1614 <= icmp_ln40_fu_815_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln37_reg_1633 <= add_ln37_fu_889_p2;
                and_ln37_3_reg_1638 <= and_ln37_3_fu_1010_p2;
                or_ln37_1_reg_1643 <= or_ln37_1_fu_1040_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_1_fu_615_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((tmp_1_fu_615_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then
                reg_507 <= xloc_1_fu_250;
                reg_512 <= xloc_2_fu_254;
                reg_517 <= xloc_3_fu_258;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state40)) then
                select_ln43_1_reg_1653 <= select_ln43_1_fu_1151_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_5_reg_1573 <= tmp_5_fu_671_p11;
                tmp_6_reg_1579 <= tmp_6_fu_691_p11;
                tmp_7_reg_1585 <= tmp_7_fu_711_p11;
                tmp_reg_1568 <= tmp_fu_651_p11;
                trunc_ln33_reg_1557 <= trunc_ln33_fu_627_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then
                x_out_0_reg <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then
                x_out_1_reg <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then
                x_out_2_reg <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then
                x_out_3_reg <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, tmp_1_fu_615_p3, ap_CS_fsm_state5, icmp_ln40_fu_815_p2, grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_done, grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done, icmp_ln35_fu_735_p2, ap_CS_fsm_state2, ap_CS_fsm_state42)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((tmp_1_fu_615_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state42;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln35_fu_735_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln40_fu_815_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state41;
                elsif (((icmp_ln35_fu_735_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln40_fu_815_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state42 => 
                if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state42;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    acc_2_fu_1053_p3 <= 
        select_ln37_2_fu_1046_p3 when (or_ln37_1_reg_1643(0) = '1') else 
        add_ln37_reg_1633;
    acc_fu_631_p9 <= "XXXXXXXXXXXXXXXX";
    add_ln33_1_fu_1193_p2 <= std_logic_vector(unsigned(indvars_iv27_fu_158) + unsigned(ap_const_lv3_7));
    add_ln33_fu_1188_p2 <= std_logic_vector(unsigned(i_1_fu_162) + unsigned(ap_const_lv3_7));
    add_ln35_fu_790_p2 <= std_logic_vector(unsigned(j_reg_382) + unsigned(ap_const_lv4_1));
    add_ln37_fu_889_p2 <= std_logic_vector(unsigned(trunc_ln3_fu_862_p4) + unsigned(zext_ln37_fu_885_p1));
    and_ln37_1_fu_972_p2 <= (xor_ln37_1_fu_966_p2 and icmp_ln37_fu_931_p2);
    and_ln37_2_fu_986_p2 <= (icmp_ln37_1_fu_946_p2 and and_ln37_fu_909_p2);
    and_ln37_3_fu_1010_p2 <= (xor_ln37_3_fu_1004_p2 and or_ln37_fu_998_p2);
    and_ln37_4_fu_1016_p2 <= (tmp_8_fu_895_p3 and select_ln37_1_fu_978_p3);
    and_ln37_5_fu_1034_p2 <= (xor_ln37_4_fu_1028_p2 and tmp_2_fu_855_p3);
    and_ln37_fu_909_p2 <= (xor_ln37_fu_903_p2 and tmp_4_fu_878_p3);
    and_ln43_1_fu_1131_p2 <= (tmp_13_fu_1059_p3 and or_ln43_1_fu_1125_p2);
    and_ln43_fu_1113_p2 <= (xor_ln43_fu_1107_p2 and or_ln43_fu_1101_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state40 <= ap_CS_fsm(39);
    ap_CS_fsm_state41 <= ap_CS_fsm(40);
    ap_CS_fsm_state42 <= ap_CS_fsm(41);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_done)
    begin
        if ((grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;
    ap_ST_fsm_state35_blk <= ap_const_logic_0;
    ap_ST_fsm_state36_blk <= ap_const_logic_0;
    ap_ST_fsm_state37_blk <= ap_const_logic_0;
    ap_ST_fsm_state38_blk <= ap_const_logic_0;
    ap_ST_fsm_state39_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state40_blk <= ap_const_logic_0;
    ap_ST_fsm_state41_blk <= ap_const_logic_0;

    ap_ST_fsm_state42_blk_assign_proc : process(grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done)
    begin
        if ((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state42_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state42_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done, ap_CS_fsm_state42)
    begin
        if ((((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_xloc_4_phi_fu_405_p4_assign_proc : process(icmp_ln40_reg_1614, select_ln43_1_reg_1653, xloc_4_reg_401, ap_CS_fsm_state41)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state41) and (icmp_ln40_reg_1614 = ap_const_lv1_0))) then 
            ap_phi_mux_xloc_4_phi_fu_405_p4 <= select_ln43_1_reg_1653;
        else 
            ap_phi_mux_xloc_4_phi_fu_405_p4 <= xloc_4_reg_401;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done, ap_CS_fsm_state42)
    begin
        if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    diag_fu_796_p9 <= "XXXXXXXXXXXXXXXX";

    grp_fu_837_ap_start_assign_proc : process(ap_CS_fsm_state5, icmp_ln40_fu_815_p2, icmp_ln35_fu_735_p2)
    begin
        if (((icmp_ln35_fu_735_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln40_fu_815_p2 = ap_const_lv1_0))) then 
            grp_fu_837_ap_start <= ap_const_logic_1;
        else 
            grp_fu_837_ap_start <= ap_const_logic_0;
        end if; 
    end process;

        grp_fu_837_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1_fu_821_p3),28));

    grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_start <= grp_upper_backsub_Pipeline_VITIS_LOOP_20_1_fu_412_ap_start_reg;
    grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_start <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_ap_start_reg;
    icmp_ln35_fu_735_p2 <= "1" when (j_reg_382 = ap_const_lv4_4) else "0";
    icmp_ln37_1_fu_946_p2 <= "1" when (tmp_11_fu_937_p4 = ap_const_lv5_1F) else "0";
    icmp_ln37_2_fu_952_p2 <= "1" when (tmp_11_fu_937_p4 = ap_const_lv5_0) else "0";
    icmp_ln37_fu_931_p2 <= "1" when (tmp_10_fu_922_p4 = ap_const_lv4_F) else "0";
    icmp_ln40_fu_815_p2 <= "1" when (diag_fu_796_p11 = ap_const_lv16_0) else "0";
    icmp_ln43_1_fu_1095_p2 <= "0" when (tmp_15_fu_1079_p4 = ap_const_lv12_0) else "1";
    icmp_ln43_fu_1089_p2 <= "0" when (tmp_15_fu_1079_p4 = ap_const_lv12_FFF) else "1";
    or_ln37_1_fu_1040_p2 <= (and_ln37_5_fu_1034_p2 or and_ln37_3_fu_1010_p2);
    or_ln37_2_fu_1022_p2 <= (and_ln37_4_fu_1016_p2 or and_ln37_2_fu_986_p2);
    or_ln37_fu_998_p2 <= (xor_ln37_2_fu_992_p2 or tmp_8_fu_895_p3);
    or_ln43_1_fu_1125_p2 <= (xor_ln43_1_fu_1119_p2 or icmp_ln43_fu_1089_p2);
    or_ln43_2_fu_1145_p2 <= (and_ln43_fu_1113_p2 or and_ln43_1_fu_1131_p2);
    or_ln43_fu_1101_p2 <= (tmp_14_fu_1071_p3 or icmp_ln43_1_fu_1095_p2);
    select_ln37_1_fu_978_p3 <= 
        and_ln37_1_fu_972_p2 when (and_ln37_fu_909_p2(0) = '1') else 
        icmp_ln37_1_fu_946_p2;
    select_ln37_2_fu_1046_p3 <= 
        ap_const_lv16_7FFF when (and_ln37_3_reg_1638(0) = '1') else 
        ap_const_lv16_8000;
    select_ln37_fu_958_p3 <= 
        icmp_ln37_1_fu_946_p2 when (and_ln37_fu_909_p2(0) = '1') else 
        icmp_ln37_2_fu_952_p2;
    select_ln43_1_fu_1151_p3 <= 
        select_ln43_fu_1137_p3 when (or_ln43_2_fu_1145_p2(0) = '1') else 
        trunc_ln43_fu_1067_p1;
    select_ln43_fu_1137_p3 <= 
        ap_const_lv16_7FFF when (and_ln43_fu_1113_p2(0) = '1') else 
        ap_const_lv16_8000;
    shl_ln1_fu_821_p3 <= (acc_1_reg_391 & ap_const_lv11_0);
    shl_ln_fu_843_p3 <= (acc_1_reg_391 & ap_const_lv11_0);
    tmp_10_fu_922_p4 <= grp_fu_1209_p3(31 downto 28);
    tmp_11_fu_937_p4 <= grp_fu_1209_p3(31 downto 27);
    tmp_12_fu_915_p3 <= grp_fu_1209_p3(27 downto 27);
    tmp_13_fu_1059_p3 <= grp_fu_837_p2(27 downto 27);
    tmp_14_fu_1071_p3 <= grp_fu_837_p2(15 downto 15);
    tmp_15_fu_1079_p4 <= grp_fu_837_p2(27 downto 16);
    tmp_1_fu_615_p3 <= i_1_fu_162(2 downto 2);
    tmp_2_fu_855_p3 <= grp_fu_1209_p3(31 downto 31);
    tmp_3_fu_871_p3 <= grp_fu_1209_p3(10 downto 10);
    tmp_4_fu_878_p3 <= grp_fu_1209_p3(26 downto 26);
    tmp_5_fu_671_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_6_fu_691_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_7_fu_711_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_8_fu_895_p3 <= add_ln37_fu_889_p2(15 downto 15);
    tmp_9_fu_745_p7 <= "XXXXXXXXXXXXXXXX";
    tmp_fu_651_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_s_fu_766_p7 <= "XXXXXXXXXXXXXXXX";
    trunc_ln33_fu_627_p1 <= i_1_fu_162(2 - 1 downto 0);
    trunc_ln35_fu_741_p1 <= j_reg_382(2 - 1 downto 0);
    trunc_ln3_fu_862_p4 <= grp_fu_1209_p3(26 downto 11);
    trunc_ln43_fu_1067_p1 <= grp_fu_837_p2(16 - 1 downto 0);

    x_out_0_assign_proc : process(grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0, grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0_ap_vld, x_out_0_reg, ap_CS_fsm_state42)
    begin
        if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then 
            x_out_0 <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0;
        else 
            x_out_0 <= x_out_0_reg;
        end if; 
    end process;

    x_out_0_ap_vld <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_0_ap_vld;

    x_out_1_assign_proc : process(grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1, grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1_ap_vld, ap_CS_fsm_state42, x_out_1_reg)
    begin
        if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then 
            x_out_1 <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1;
        else 
            x_out_1 <= x_out_1_reg;
        end if; 
    end process;

    x_out_1_ap_vld <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_1_ap_vld;

    x_out_2_assign_proc : process(grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2, grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2_ap_vld, ap_CS_fsm_state42, x_out_2_reg)
    begin
        if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then 
            x_out_2 <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2;
        else 
            x_out_2 <= x_out_2_reg;
        end if; 
    end process;

    x_out_2_ap_vld <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_2_ap_vld;

    x_out_3_assign_proc : process(grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3, grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3_ap_vld, ap_CS_fsm_state42, x_out_3_reg)
    begin
        if (((grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state42))) then 
            x_out_3 <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3;
        else 
            x_out_3 <= x_out_3_reg;
        end if; 
    end process;

    x_out_3_ap_vld <= grp_upper_backsub_Pipeline_VITIS_LOOP_48_6_fu_476_x_out_3_ap_vld;
    xor_ln37_1_fu_966_p2 <= (tmp_12_fu_915_p3 xor ap_const_lv1_1);
    xor_ln37_2_fu_992_p2 <= (select_ln37_fu_958_p3 xor ap_const_lv1_1);
    xor_ln37_3_fu_1004_p2 <= (tmp_2_fu_855_p3 xor ap_const_lv1_1);
    xor_ln37_4_fu_1028_p2 <= (or_ln37_2_fu_1022_p2 xor ap_const_lv1_1);
    xor_ln37_fu_903_p2 <= (tmp_8_fu_895_p3 xor ap_const_lv1_1);
    xor_ln43_1_fu_1119_p2 <= (tmp_14_fu_1071_p3 xor ap_const_lv1_1);
    xor_ln43_fu_1107_p2 <= (tmp_13_fu_1059_p3 xor ap_const_lv1_1);
    zext_ln33_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(indvars_iv27_fu_158),4));
    zext_ln37_fu_885_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_871_p3),16));
end behav;
