-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity solve_top_mat_vec_mul is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
    vec_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    vec_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    vec_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    vec_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    res_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_0_ap_vld : OUT STD_LOGIC;
    res_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_1_ap_vld : OUT STD_LOGIC;
    res_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_2_ap_vld : OUT STD_LOGIC;
    res_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_3_ap_vld : OUT STD_LOGIC );
end;


architecture behav of solve_top_mat_vec_mul is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_done : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_idle : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_ready : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_done : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_idle : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_ready : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_idle : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_ready : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_idle : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_ready : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld : STD_LOGIC;
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg : STD_LOGIC := '0';
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal res_0_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal res_3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal res_2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal res_1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_24_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_1_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_1_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_2_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_2_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_3_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_3_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_4_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_4_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_5_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_5_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_6_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_6_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_7_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_7_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_8_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_8_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_9_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_9_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_10_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_10_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_11_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_11_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_12_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_12_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_13_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_13_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_14_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_14_load_out_ap_vld : OUT STD_LOGIC;
        mat_local_15_load_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        mat_local_15_load_out_ap_vld : OUT STD_LOGIC );
    end component;


    component solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_29_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vec_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
        vec_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
        vec_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
        vec_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC );
    end component;


    component solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_40_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mat_local_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_1_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_2_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_3_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        conv7_i : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_4_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_5_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_6_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_7_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        conv7_i_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_8_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_9_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_10_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_11_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        conv7_i_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_12_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_13_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_14_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        mat_local_15_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        conv7_i_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        res_local_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_local_3_out_ap_vld : OUT STD_LOGIC;
        res_local_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_local_2_out_ap_vld : OUT STD_LOGIC;
        res_local_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_local_1_out_ap_vld : OUT STD_LOGIC;
        res_local_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_local_out_ap_vld : OUT STD_LOGIC );
    end component;


    component solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_50_7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        res_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_0_ap_vld : OUT STD_LOGIC;
        res_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_3_ap_vld : OUT STD_LOGIC;
        res_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_2_ap_vld : OUT STD_LOGIC;
        res_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_1_ap_vld : OUT STD_LOGIC;
        res_local_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        res_local_1_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        res_local_2_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        res_local_3_reload : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276 : component solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_24_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start,
        ap_done => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_done,
        ap_idle => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_idle,
        ap_ready => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_ready,
        p_read => p_read,
        p_read1 => p_read1,
        p_read2 => p_read2,
        p_read3 => p_read3,
        p_read4 => p_read4,
        p_read5 => p_read5,
        p_read6 => p_read6,
        p_read7 => p_read7,
        p_read8 => p_read8,
        p_read9 => p_read9,
        p_read10 => p_read10,
        p_read11 => p_read11,
        p_read12 => p_read12,
        p_read13 => p_read13,
        p_read14 => p_read14,
        p_read15 => p_read15,
        mat_local_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out,
        mat_local_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out_ap_vld,
        mat_local_1_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out,
        mat_local_1_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out_ap_vld,
        mat_local_2_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out,
        mat_local_2_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out_ap_vld,
        mat_local_3_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out,
        mat_local_3_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out_ap_vld,
        mat_local_4_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out,
        mat_local_4_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out_ap_vld,
        mat_local_5_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out,
        mat_local_5_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out_ap_vld,
        mat_local_6_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out,
        mat_local_6_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out_ap_vld,
        mat_local_7_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out,
        mat_local_7_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out_ap_vld,
        mat_local_8_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out,
        mat_local_8_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out_ap_vld,
        mat_local_9_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out,
        mat_local_9_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out_ap_vld,
        mat_local_10_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out,
        mat_local_10_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out_ap_vld,
        mat_local_11_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out,
        mat_local_11_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out_ap_vld,
        mat_local_12_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out,
        mat_local_12_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out_ap_vld,
        mat_local_13_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out,
        mat_local_13_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out_ap_vld,
        mat_local_14_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out,
        mat_local_14_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out_ap_vld,
        mat_local_15_load_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out,
        mat_local_15_load_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out_ap_vld);

    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328 : component solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_29_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start,
        ap_done => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_done,
        ap_idle => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_idle,
        ap_ready => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_ready,
        vec_0_val => vec_0_val,
        vec_1_val => vec_1_val,
        vec_2_val => vec_2_val,
        vec_3_val => vec_3_val,
        p_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out,
        p_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out_ap_vld,
        p_out1 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1,
        p_out1_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1_ap_vld,
        p_out2 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2,
        p_out2_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2_ap_vld,
        p_out3 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3,
        p_out3_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3_ap_vld);

    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344 : component solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_40_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start,
        ap_done => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done,
        ap_idle => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_idle,
        ap_ready => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_ready,
        mat_local_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_load_out,
        mat_local_1_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_1_load_out,
        mat_local_2_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_2_load_out,
        mat_local_3_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_3_load_out,
        conv7_i => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out3,
        mat_local_4_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_4_load_out,
        mat_local_5_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_5_load_out,
        mat_local_6_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_6_load_out,
        mat_local_7_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_7_load_out,
        conv7_i_1 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out2,
        mat_local_8_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_8_load_out,
        mat_local_9_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_9_load_out,
        mat_local_10_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_10_load_out,
        mat_local_11_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_11_load_out,
        conv7_i_2 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out1,
        mat_local_12_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_12_load_out,
        mat_local_13_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_13_load_out,
        mat_local_14_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_14_load_out,
        mat_local_15_load_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_mat_local_15_load_out,
        conv7_i_3 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_p_out,
        res_local_3_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out,
        res_local_3_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out_ap_vld,
        res_local_2_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out,
        res_local_2_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out_ap_vld,
        res_local_1_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out,
        res_local_1_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out_ap_vld,
        res_local_out => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out,
        res_local_out_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out_ap_vld);

    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372 : component solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_50_7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start,
        ap_done => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done,
        ap_idle => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_idle,
        ap_ready => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_ready,
        res_0 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0,
        res_0_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld,
        res_3 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3,
        res_3_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld,
        res_2 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2,
        res_2_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld,
        res_1 => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1,
        res_1_ap_vld => grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld,
        res_local_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_out,
        res_local_1_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_1_out,
        res_local_2_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_2_out,
        res_local_3_reload => grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_res_local_3_out);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_ready = ap_const_logic_1)) then 
                    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_ready = ap_const_logic_1)) then 
                    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_ready = ap_const_logic_1)) then 
                    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_ready = ap_const_logic_1)) then 
                    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                res_0_reg <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                res_1_reg <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                res_2_reg <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                res_3_reg <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done, grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done)
    begin
        if ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done)
    begin
        if ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_done, grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_done = ap_const_logic_0) or (grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done, ap_CS_fsm_state6)
    begin
        if ((((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done, ap_CS_fsm_state6)
    begin
        if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_24_1_fu_276_ap_start_reg;
    grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_29_3_fu_328_ap_start_reg;
    grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_40_5_fu_344_ap_start_reg;
    grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_ap_start_reg;

    res_0_assign_proc : process(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0, grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld, res_0_reg, ap_CS_fsm_state6)
    begin
        if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_0 <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0;
        else 
            res_0 <= res_0_reg;
        end if; 
    end process;

    res_0_ap_vld <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_0_ap_vld;

    res_1_assign_proc : process(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1, grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld, ap_CS_fsm_state6, res_1_reg)
    begin
        if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_1 <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1;
        else 
            res_1 <= res_1_reg;
        end if; 
    end process;

    res_1_ap_vld <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_1_ap_vld;

    res_2_assign_proc : process(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2, grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld, ap_CS_fsm_state6, res_2_reg)
    begin
        if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_2 <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2;
        else 
            res_2 <= res_2_reg;
        end if; 
    end process;

    res_2_ap_vld <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_2_ap_vld;

    res_3_assign_proc : process(grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3, grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld, ap_CS_fsm_state6, res_3_reg)
    begin
        if (((grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_3 <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3;
        else 
            res_3 <= res_3_reg;
        end if; 
    end process;

    res_3_ap_vld <= grp_mat_vec_mul_Pipeline_VITIS_LOOP_50_7_fu_372_res_3_ap_vld;
end behav;
