-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity solve_top_decompose_qr_Pipeline_VITIS_LOOP_70_8_VITIS_LOOP_71_9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    R_out_0_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_0_0_ap_vld : OUT STD_LOGIC;
    R_out_3_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_3_3_ap_vld : OUT STD_LOGIC;
    R_out_3_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_3_2_ap_vld : OUT STD_LOGIC;
    R_out_3_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_3_1_ap_vld : OUT STD_LOGIC;
    R_out_3_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_3_0_ap_vld : OUT STD_LOGIC;
    R_out_2_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_2_3_ap_vld : OUT STD_LOGIC;
    R_out_2_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_2_2_ap_vld : OUT STD_LOGIC;
    R_out_2_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_2_1_ap_vld : OUT STD_LOGIC;
    R_out_2_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_2_0_ap_vld : OUT STD_LOGIC;
    R_out_1_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_1_3_ap_vld : OUT STD_LOGIC;
    R_out_1_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_1_2_ap_vld : OUT STD_LOGIC;
    R_out_1_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_1_1_ap_vld : OUT STD_LOGIC;
    R_out_1_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_1_0_ap_vld : OUT STD_LOGIC;
    R_out_0_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_0_3_ap_vld : OUT STD_LOGIC;
    R_out_0_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_0_2_ap_vld : OUT STD_LOGIC;
    R_out_0_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_out_0_1_ap_vld : OUT STD_LOGIC;
    local_aug_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_1_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_2_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_3_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_4_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_5_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_6_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_7_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_8_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_9_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_10_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_11_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_12_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_13_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_14_load : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_15_load : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of solve_top_decompose_qr_Pipeline_VITIS_LOOP_70_8_VITIS_LOOP_71_9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln70_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal trunc_ln70_fu_405_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln70_reg_617 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln71_fu_410_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln71_reg_621 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln72_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_625 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_180_fu_516_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_180_reg_630 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_fu_112 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln71_fu_550_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal r_1_fu_116 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln70_1_fu_397_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_r_1_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_fu_120 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln70_1_fu_365_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (4 downto 0);
    signal ref_tmp143_1_fu_571_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln71_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln70_fu_377_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln70_fu_389_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_420_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_177_fu_444_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_178_fu_468_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_179_fu_492_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_420_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_177_fu_444_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_178_fu_468_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_179_fu_492_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_180_fu_516_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_180_fu_516_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_s_fu_420_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_420_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_420_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_420_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_177_fu_444_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_177_fu_444_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_177_fu_444_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_177_fu_444_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_178_fu_468_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_178_fu_468_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_178_fu_468_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_178_fu_468_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_179_fu_492_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_179_fu_492_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_179_fu_492_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_179_fu_492_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_180_fu_516_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_180_fu_516_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_180_fu_516_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_180_fu_516_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component solve_top_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component solve_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_16_1_1_U177 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => local_aug_load,
        din1 => local_aug_1_load,
        din2 => local_aug_2_load,
        din3 => local_aug_3_load,
        def => tmp_s_fu_420_p9,
        sel => trunc_ln70_fu_405_p1,
        dout => tmp_s_fu_420_p11);

    sparsemux_9_2_16_1_1_U178 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => local_aug_4_load,
        din1 => local_aug_5_load,
        din2 => local_aug_6_load,
        din3 => local_aug_7_load,
        def => tmp_177_fu_444_p9,
        sel => trunc_ln70_fu_405_p1,
        dout => tmp_177_fu_444_p11);

    sparsemux_9_2_16_1_1_U179 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => local_aug_8_load,
        din1 => local_aug_9_load,
        din2 => local_aug_10_load,
        din3 => local_aug_11_load,
        def => tmp_178_fu_468_p9,
        sel => trunc_ln70_fu_405_p1,
        dout => tmp_178_fu_468_p11);

    sparsemux_9_2_16_1_1_U180 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => local_aug_12_load,
        din1 => local_aug_13_load,
        din2 => local_aug_14_load,
        din3 => local_aug_15_load,
        def => tmp_179_fu_492_p9,
        sel => trunc_ln70_fu_405_p1,
        dout => tmp_179_fu_492_p11);

    sparsemux_9_2_16_1_1_U181 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => tmp_s_fu_420_p11,
        din1 => tmp_177_fu_444_p11,
        din2 => tmp_178_fu_468_p11,
        din3 => tmp_179_fu_492_p11,
        def => tmp_180_fu_516_p9,
        sel => tmp_180_fu_516_p10,
        dout => tmp_180_fu_516_p11);

    flow_control_loop_pipe_sequential_init_U : component solve_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    c_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln70_fu_359_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_112 <= add_ln71_fu_550_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_112 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln70_fu_359_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_120 <= add_ln70_1_fu_365_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_120 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    r_1_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln70_fu_359_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    r_1_fu_116 <= select_ln70_1_fu_397_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    r_1_fu_116 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln72_reg_625 <= icmp_ln72_fu_414_p2;
                tmp_180_reg_630 <= tmp_180_fu_516_p11;
                trunc_ln70_reg_617 <= trunc_ln70_fu_405_p1;
                trunc_ln71_reg_621 <= trunc_ln71_fu_410_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    R_out_0_0 <= ref_tmp143_1_fu_571_p3;

    R_out_0_0_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_0) and (trunc_ln70_reg_617 = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_0_0_ap_vld <= ap_const_logic_1;
        else 
            R_out_0_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_0_1 <= ref_tmp143_1_fu_571_p3;

    R_out_0_1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_0) and (trunc_ln70_reg_617 = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_0_1_ap_vld <= ap_const_logic_1;
        else 
            R_out_0_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_0_2 <= ref_tmp143_1_fu_571_p3;

    R_out_0_2_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_0) and (trunc_ln70_reg_617 = ap_const_lv2_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_0_2_ap_vld <= ap_const_logic_1;
        else 
            R_out_0_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_0_3 <= ref_tmp143_1_fu_571_p3;

    R_out_0_3_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_0) and (trunc_ln70_reg_617 = ap_const_lv2_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_0_3_ap_vld <= ap_const_logic_1;
        else 
            R_out_0_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_1_0 <= ref_tmp143_1_fu_571_p3;

    R_out_1_0_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_1) and (trunc_ln70_reg_617 = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_1_0_ap_vld <= ap_const_logic_1;
        else 
            R_out_1_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_1_1 <= ref_tmp143_1_fu_571_p3;

    R_out_1_1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_1) and (trunc_ln70_reg_617 = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_1_1_ap_vld <= ap_const_logic_1;
        else 
            R_out_1_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_1_2 <= ref_tmp143_1_fu_571_p3;

    R_out_1_2_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_1) and (trunc_ln70_reg_617 = ap_const_lv2_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_1_2_ap_vld <= ap_const_logic_1;
        else 
            R_out_1_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_1_3 <= ref_tmp143_1_fu_571_p3;

    R_out_1_3_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_1) and (trunc_ln70_reg_617 = ap_const_lv2_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_1_3_ap_vld <= ap_const_logic_1;
        else 
            R_out_1_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_2_0 <= ref_tmp143_1_fu_571_p3;

    R_out_2_0_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_2) and (trunc_ln70_reg_617 = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_2_0_ap_vld <= ap_const_logic_1;
        else 
            R_out_2_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_2_1 <= ref_tmp143_1_fu_571_p3;

    R_out_2_1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_2) and (trunc_ln70_reg_617 = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_2_1_ap_vld <= ap_const_logic_1;
        else 
            R_out_2_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_2_2 <= ref_tmp143_1_fu_571_p3;

    R_out_2_2_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_2) and (trunc_ln70_reg_617 = ap_const_lv2_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_2_2_ap_vld <= ap_const_logic_1;
        else 
            R_out_2_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_2_3 <= ref_tmp143_1_fu_571_p3;

    R_out_2_3_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_2) and (trunc_ln70_reg_617 = ap_const_lv2_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_2_3_ap_vld <= ap_const_logic_1;
        else 
            R_out_2_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_3_0 <= ref_tmp143_1_fu_571_p3;

    R_out_3_0_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_3) and (trunc_ln70_reg_617 = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_3_0_ap_vld <= ap_const_logic_1;
        else 
            R_out_3_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_3_1 <= ref_tmp143_1_fu_571_p3;

    R_out_3_1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_3) and (trunc_ln70_reg_617 = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_3_1_ap_vld <= ap_const_logic_1;
        else 
            R_out_3_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_3_2 <= ref_tmp143_1_fu_571_p3;

    R_out_3_2_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_3) and (trunc_ln70_reg_617 = ap_const_lv2_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_3_2_ap_vld <= ap_const_logic_1;
        else 
            R_out_3_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_out_3_3 <= ref_tmp143_1_fu_571_p3;

    R_out_3_3_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln70_reg_617, ap_block_pp0_stage0_11001, trunc_ln71_reg_621)
    begin
        if (((trunc_ln71_reg_621 = ap_const_lv2_3) and (trunc_ln70_reg_617 = ap_const_lv2_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_3_3_ap_vld <= ap_const_logic_1;
        else 
            R_out_3_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln70_1_fu_365_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv5_1));
    add_ln70_fu_377_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_r_1_load) + unsigned(ap_const_lv3_1));
    add_ln71_fu_550_p2 <= std_logic_vector(unsigned(select_ln70_fu_389_p3) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln70_fu_359_p2)
    begin
        if (((icmp_ln70_fu_359_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, c_fu_112, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_112;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten_fu_120)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_120;
        end if; 
    end process;


    ap_sig_allocacmp_r_1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, r_1_fu_116)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_r_1_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_r_1_load <= r_1_fu_116;
        end if; 
    end process;

    icmp_ln70_fu_359_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv5_10) else "0";
    icmp_ln71_fu_383_p2 <= "1" when (ap_sig_allocacmp_c_load = ap_const_lv3_4) else "0";
    icmp_ln72_fu_414_p2 <= "1" when (unsigned(select_ln70_fu_389_p3) < unsigned(select_ln70_1_fu_397_p3)) else "0";
    ref_tmp143_1_fu_571_p3 <= 
        ap_const_lv16_0 when (icmp_ln72_reg_625(0) = '1') else 
        tmp_180_reg_630;
    select_ln70_1_fu_397_p3 <= 
        add_ln70_fu_377_p2 when (icmp_ln71_fu_383_p2(0) = '1') else 
        ap_sig_allocacmp_r_1_load;
    select_ln70_fu_389_p3 <= 
        ap_const_lv3_0 when (icmp_ln71_fu_383_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    tmp_177_fu_444_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_178_fu_468_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_179_fu_492_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_180_fu_516_p10 <= select_ln70_fu_389_p3(2 - 1 downto 0);
    tmp_180_fu_516_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_s_fu_420_p9 <= "XXXXXXXXXXXXXXXX";
    trunc_ln70_fu_405_p1 <= select_ln70_1_fu_397_p3(2 - 1 downto 0);
    trunc_ln71_fu_410_p1 <= select_ln70_fu_389_p3(2 - 1 downto 0);
end behav;
