// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_24_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        mat_local_load_out,
        mat_local_load_out_ap_vld,
        mat_local_1_load_out,
        mat_local_1_load_out_ap_vld,
        mat_local_2_load_out,
        mat_local_2_load_out_ap_vld,
        mat_local_3_load_out,
        mat_local_3_load_out_ap_vld,
        mat_local_4_load_out,
        mat_local_4_load_out_ap_vld,
        mat_local_5_load_out,
        mat_local_5_load_out_ap_vld,
        mat_local_6_load_out,
        mat_local_6_load_out_ap_vld,
        mat_local_7_load_out,
        mat_local_7_load_out_ap_vld,
        mat_local_8_load_out,
        mat_local_8_load_out_ap_vld,
        mat_local_9_load_out,
        mat_local_9_load_out_ap_vld,
        mat_local_10_load_out,
        mat_local_10_load_out_ap_vld,
        mat_local_11_load_out,
        mat_local_11_load_out_ap_vld,
        mat_local_12_load_out,
        mat_local_12_load_out_ap_vld,
        mat_local_13_load_out,
        mat_local_13_load_out_ap_vld,
        mat_local_14_load_out,
        mat_local_14_load_out_ap_vld,
        mat_local_15_load_out,
        mat_local_15_load_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
output  [15:0] mat_local_load_out;
output   mat_local_load_out_ap_vld;
output  [15:0] mat_local_1_load_out;
output   mat_local_1_load_out_ap_vld;
output  [15:0] mat_local_2_load_out;
output   mat_local_2_load_out_ap_vld;
output  [15:0] mat_local_3_load_out;
output   mat_local_3_load_out_ap_vld;
output  [15:0] mat_local_4_load_out;
output   mat_local_4_load_out_ap_vld;
output  [15:0] mat_local_5_load_out;
output   mat_local_5_load_out_ap_vld;
output  [15:0] mat_local_6_load_out;
output   mat_local_6_load_out_ap_vld;
output  [15:0] mat_local_7_load_out;
output   mat_local_7_load_out_ap_vld;
output  [15:0] mat_local_8_load_out;
output   mat_local_8_load_out_ap_vld;
output  [15:0] mat_local_9_load_out;
output   mat_local_9_load_out_ap_vld;
output  [15:0] mat_local_10_load_out;
output   mat_local_10_load_out_ap_vld;
output  [15:0] mat_local_11_load_out;
output   mat_local_11_load_out_ap_vld;
output  [15:0] mat_local_12_load_out;
output   mat_local_12_load_out_ap_vld;
output  [15:0] mat_local_13_load_out;
output   mat_local_13_load_out_ap_vld;
output  [15:0] mat_local_14_load_out;
output   mat_local_14_load_out_ap_vld;
output  [15:0] mat_local_15_load_out;
output   mat_local_15_load_out_ap_vld;

reg ap_idle;
reg mat_local_load_out_ap_vld;
reg mat_local_1_load_out_ap_vld;
reg mat_local_2_load_out_ap_vld;
reg mat_local_3_load_out_ap_vld;
reg mat_local_4_load_out_ap_vld;
reg mat_local_5_load_out_ap_vld;
reg mat_local_6_load_out_ap_vld;
reg mat_local_7_load_out_ap_vld;
reg mat_local_8_load_out_ap_vld;
reg mat_local_9_load_out_ap_vld;
reg mat_local_10_load_out_ap_vld;
reg mat_local_11_load_out_ap_vld;
reg mat_local_12_load_out_ap_vld;
reg mat_local_13_load_out_ap_vld;
reg mat_local_14_load_out_ap_vld;
reg mat_local_15_load_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln24_fu_390_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] i_fu_106;
wire   [2:0] add_ln24_fu_396_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_4;
reg   [15:0] mat_local_15_fu_110;
wire   [15:0] mat_local_18_fu_478_p11;
wire   [1:0] trunc_ln24_fu_402_p1;
reg   [15:0] mat_local_14_fu_114;
reg   [15:0] mat_local_13_fu_118;
reg   [15:0] mat_local_12_fu_122;
reg   [15:0] mat_local_11_fu_126;
wire   [15:0] mat_local_17_fu_454_p11;
reg   [15:0] mat_local_10_fu_130;
reg   [15:0] mat_local_9_fu_134;
reg   [15:0] mat_local_8_fu_138;
reg   [15:0] mat_local_7_fu_142;
wire   [15:0] mat_local_16_fu_430_p11;
reg   [15:0] mat_local_6_fu_146;
reg   [15:0] mat_local_5_fu_150;
reg   [15:0] mat_local_4_fu_154;
reg   [15:0] mat_local_3_fu_158;
wire   [15:0] mat_local_19_fu_406_p11;
reg   [15:0] mat_local_2_fu_162;
reg   [15:0] mat_local_1_fu_166;
reg   [15:0] mat_local_fu_170;
wire   [15:0] mat_local_19_fu_406_p9;
wire   [15:0] mat_local_16_fu_430_p9;
wire   [15:0] mat_local_17_fu_454_p9;
wire   [15:0] mat_local_18_fu_478_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] mat_local_19_fu_406_p1;
wire   [1:0] mat_local_19_fu_406_p3;
wire  signed [1:0] mat_local_19_fu_406_p5;
wire  signed [1:0] mat_local_19_fu_406_p7;
wire   [1:0] mat_local_16_fu_430_p1;
wire   [1:0] mat_local_16_fu_430_p3;
wire  signed [1:0] mat_local_16_fu_430_p5;
wire  signed [1:0] mat_local_16_fu_430_p7;
wire   [1:0] mat_local_17_fu_454_p1;
wire   [1:0] mat_local_17_fu_454_p3;
wire  signed [1:0] mat_local_17_fu_454_p5;
wire  signed [1:0] mat_local_17_fu_454_p7;
wire   [1:0] mat_local_18_fu_478_p1;
wire   [1:0] mat_local_18_fu_478_p3;
wire  signed [1:0] mat_local_18_fu_478_p5;
wire  signed [1:0] mat_local_18_fu_478_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_106 = 3'd0;
#0 mat_local_15_fu_110 = 16'd0;
#0 mat_local_14_fu_114 = 16'd0;
#0 mat_local_13_fu_118 = 16'd0;
#0 mat_local_12_fu_122 = 16'd0;
#0 mat_local_11_fu_126 = 16'd0;
#0 mat_local_10_fu_130 = 16'd0;
#0 mat_local_9_fu_134 = 16'd0;
#0 mat_local_8_fu_138 = 16'd0;
#0 mat_local_7_fu_142 = 16'd0;
#0 mat_local_6_fu_146 = 16'd0;
#0 mat_local_5_fu_150 = 16'd0;
#0 mat_local_4_fu_154 = 16'd0;
#0 mat_local_3_fu_158 = 16'd0;
#0 mat_local_2_fu_162 = 16'd0;
#0 mat_local_1_fu_166 = 16'd0;
#0 mat_local_fu_170 = 16'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U321(
    .din0(p_read),
    .din1(p_read1),
    .din2(p_read2),
    .din3(p_read3),
    .def(mat_local_19_fu_406_p9),
    .sel(trunc_ln24_fu_402_p1),
    .dout(mat_local_19_fu_406_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U322(
    .din0(p_read4),
    .din1(p_read5),
    .din2(p_read6),
    .din3(p_read7),
    .def(mat_local_16_fu_430_p9),
    .sel(trunc_ln24_fu_402_p1),
    .dout(mat_local_16_fu_430_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U323(
    .din0(p_read8),
    .din1(p_read9),
    .din2(p_read10),
    .din3(p_read11),
    .def(mat_local_17_fu_454_p9),
    .sel(trunc_ln24_fu_402_p1),
    .dout(mat_local_17_fu_454_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U324(
    .din0(p_read12),
    .din1(p_read13),
    .din2(p_read14),
    .din3(p_read15),
    .def(mat_local_18_fu_478_p9),
    .sel(trunc_ln24_fu_402_p1),
    .dout(mat_local_18_fu_478_p11)
);

solve_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln24_fu_390_p2 == 1'd0)) begin
            i_fu_106 <= add_ln24_fu_396_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_106 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln24_fu_402_p1 == 2'd2) & (icmp_ln24_fu_390_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_10_fu_130 <= mat_local_17_fu_454_p11;
        mat_local_14_fu_114 <= mat_local_18_fu_478_p11;
        mat_local_2_fu_162 <= mat_local_19_fu_406_p11;
        mat_local_6_fu_146 <= mat_local_16_fu_430_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln24_fu_402_p1 == 2'd3) & (icmp_ln24_fu_390_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_11_fu_126 <= mat_local_17_fu_454_p11;
        mat_local_15_fu_110 <= mat_local_18_fu_478_p11;
        mat_local_3_fu_158 <= mat_local_19_fu_406_p11;
        mat_local_7_fu_142 <= mat_local_16_fu_430_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln24_fu_402_p1 == 2'd0) & (icmp_ln24_fu_390_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_12_fu_122 <= mat_local_18_fu_478_p11;
        mat_local_4_fu_154 <= mat_local_16_fu_430_p11;
        mat_local_8_fu_138 <= mat_local_17_fu_454_p11;
        mat_local_fu_170 <= mat_local_19_fu_406_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln24_fu_402_p1 == 2'd1) & (icmp_ln24_fu_390_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_13_fu_118 <= mat_local_18_fu_478_p11;
        mat_local_1_fu_166 <= mat_local_19_fu_406_p11;
        mat_local_5_fu_150 <= mat_local_16_fu_430_p11;
        mat_local_9_fu_134 <= mat_local_17_fu_454_p11;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_4 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_106;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_10_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_10_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_11_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_11_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_12_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_12_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_13_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_13_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_14_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_14_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_15_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_15_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_1_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_1_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_2_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_3_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_3_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_4_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_4_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_5_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_5_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_6_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_6_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_7_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_7_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_8_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_8_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_9_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_9_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln24_fu_390_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_local_load_out_ap_vld = 1'b1;
    end else begin
        mat_local_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_396_p2 = (ap_sig_allocacmp_i_4 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln24_fu_390_p2 = ((ap_sig_allocacmp_i_4 == 3'd4) ? 1'b1 : 1'b0);

assign mat_local_10_load_out = mat_local_10_fu_130;

assign mat_local_11_load_out = mat_local_11_fu_126;

assign mat_local_12_load_out = mat_local_12_fu_122;

assign mat_local_13_load_out = mat_local_13_fu_118;

assign mat_local_14_load_out = mat_local_14_fu_114;

assign mat_local_15_load_out = mat_local_15_fu_110;

assign mat_local_16_fu_430_p9 = 'bx;

assign mat_local_17_fu_454_p9 = 'bx;

assign mat_local_18_fu_478_p9 = 'bx;

assign mat_local_19_fu_406_p9 = 'bx;

assign mat_local_1_load_out = mat_local_1_fu_166;

assign mat_local_2_load_out = mat_local_2_fu_162;

assign mat_local_3_load_out = mat_local_3_fu_158;

assign mat_local_4_load_out = mat_local_4_fu_154;

assign mat_local_5_load_out = mat_local_5_fu_150;

assign mat_local_6_load_out = mat_local_6_fu_146;

assign mat_local_7_load_out = mat_local_7_fu_142;

assign mat_local_8_load_out = mat_local_8_fu_138;

assign mat_local_9_load_out = mat_local_9_fu_134;

assign mat_local_load_out = mat_local_fu_170;

assign trunc_ln24_fu_402_p1 = ap_sig_allocacmp_i_4[1:0];

endmodule //solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_24_1
