// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module solve_top_upper_backsub_Pipeline_VITIS_LOOP_20_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_in_0_val,
        y_in_1_val,
        y_in_2_val,
        y_in_3_val,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        yloc_3_out,
        yloc_3_out_ap_vld,
        yloc_2_out,
        yloc_2_out_ap_vld,
        yloc_1_out,
        yloc_1_out_ap_vld,
        yloc_out,
        yloc_out_ap_vld,
        Rloc_load_out,
        Rloc_load_out_ap_vld,
        Rloc_1_load_out,
        Rloc_1_load_out_ap_vld,
        Rloc_2_load_out,
        Rloc_2_load_out_ap_vld,
        Rloc_3_load_out,
        Rloc_3_load_out_ap_vld,
        Rloc_4_load_out,
        Rloc_4_load_out_ap_vld,
        Rloc_5_load_out,
        Rloc_5_load_out_ap_vld,
        Rloc_6_load_out,
        Rloc_6_load_out_ap_vld,
        Rloc_7_load_out,
        Rloc_7_load_out_ap_vld,
        Rloc_8_load_out,
        Rloc_8_load_out_ap_vld,
        Rloc_9_load_out,
        Rloc_9_load_out_ap_vld,
        Rloc_10_load_out,
        Rloc_10_load_out_ap_vld,
        Rloc_11_load_out,
        Rloc_11_load_out_ap_vld,
        Rloc_12_load_out,
        Rloc_12_load_out_ap_vld,
        Rloc_13_load_out,
        Rloc_13_load_out_ap_vld,
        Rloc_14_load_out,
        Rloc_14_load_out_ap_vld,
        Rloc_15_load_out,
        Rloc_15_load_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] y_in_0_val;
input  [15:0] y_in_1_val;
input  [15:0] y_in_2_val;
input  [15:0] y_in_3_val;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
output  [15:0] yloc_3_out;
output   yloc_3_out_ap_vld;
output  [15:0] yloc_2_out;
output   yloc_2_out_ap_vld;
output  [15:0] yloc_1_out;
output   yloc_1_out_ap_vld;
output  [15:0] yloc_out;
output   yloc_out_ap_vld;
output  [15:0] Rloc_load_out;
output   Rloc_load_out_ap_vld;
output  [15:0] Rloc_1_load_out;
output   Rloc_1_load_out_ap_vld;
output  [15:0] Rloc_2_load_out;
output   Rloc_2_load_out_ap_vld;
output  [15:0] Rloc_3_load_out;
output   Rloc_3_load_out_ap_vld;
output  [15:0] Rloc_4_load_out;
output   Rloc_4_load_out_ap_vld;
output  [15:0] Rloc_5_load_out;
output   Rloc_5_load_out_ap_vld;
output  [15:0] Rloc_6_load_out;
output   Rloc_6_load_out_ap_vld;
output  [15:0] Rloc_7_load_out;
output   Rloc_7_load_out_ap_vld;
output  [15:0] Rloc_8_load_out;
output   Rloc_8_load_out_ap_vld;
output  [15:0] Rloc_9_load_out;
output   Rloc_9_load_out_ap_vld;
output  [15:0] Rloc_10_load_out;
output   Rloc_10_load_out_ap_vld;
output  [15:0] Rloc_11_load_out;
output   Rloc_11_load_out_ap_vld;
output  [15:0] Rloc_12_load_out;
output   Rloc_12_load_out_ap_vld;
output  [15:0] Rloc_13_load_out;
output   Rloc_13_load_out_ap_vld;
output  [15:0] Rloc_14_load_out;
output   Rloc_14_load_out_ap_vld;
output  [15:0] Rloc_15_load_out;
output   Rloc_15_load_out_ap_vld;

reg ap_idle;
reg yloc_3_out_ap_vld;
reg yloc_2_out_ap_vld;
reg yloc_1_out_ap_vld;
reg yloc_out_ap_vld;
reg Rloc_load_out_ap_vld;
reg Rloc_1_load_out_ap_vld;
reg Rloc_2_load_out_ap_vld;
reg Rloc_3_load_out_ap_vld;
reg Rloc_4_load_out_ap_vld;
reg Rloc_5_load_out_ap_vld;
reg Rloc_6_load_out_ap_vld;
reg Rloc_7_load_out_ap_vld;
reg Rloc_8_load_out_ap_vld;
reg Rloc_9_load_out_ap_vld;
reg Rloc_10_load_out_ap_vld;
reg Rloc_11_load_out_ap_vld;
reg Rloc_12_load_out_ap_vld;
reg Rloc_13_load_out_ap_vld;
reg Rloc_14_load_out_ap_vld;
reg Rloc_15_load_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln20_fu_474_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] i_fu_122;
wire   [2:0] add_ln20_fu_480_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_2;
reg   [15:0] yloc_fu_126;
wire   [15:0] yloc_4_fu_490_p11;
wire   [1:0] trunc_ln20_fu_486_p1;
reg   [15:0] yloc_1_fu_130;
reg   [15:0] yloc_2_fu_134;
reg   [15:0] yloc_3_fu_138;
reg   [15:0] Rloc_15_fu_142;
wire   [15:0] Rloc_18_fu_586_p11;
reg   [15:0] Rloc_14_fu_146;
reg   [15:0] Rloc_13_fu_150;
reg   [15:0] Rloc_12_fu_154;
reg   [15:0] Rloc_11_fu_158;
wire   [15:0] Rloc_17_fu_562_p11;
reg   [15:0] Rloc_10_fu_162;
reg   [15:0] Rloc_9_fu_166;
reg   [15:0] Rloc_8_fu_170;
reg   [15:0] Rloc_7_fu_174;
wire   [15:0] Rloc_16_fu_538_p11;
reg   [15:0] Rloc_6_fu_178;
reg   [15:0] Rloc_5_fu_182;
reg   [15:0] Rloc_4_fu_186;
reg   [15:0] Rloc_3_fu_190;
wire   [15:0] Rloc_19_fu_514_p11;
reg   [15:0] Rloc_2_fu_194;
reg   [15:0] Rloc_1_fu_198;
reg   [15:0] Rloc_fu_202;
wire   [15:0] yloc_4_fu_490_p9;
wire   [15:0] Rloc_19_fu_514_p9;
wire   [15:0] Rloc_16_fu_538_p9;
wire   [15:0] Rloc_17_fu_562_p9;
wire   [15:0] Rloc_18_fu_586_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] yloc_4_fu_490_p1;
wire   [1:0] yloc_4_fu_490_p3;
wire  signed [1:0] yloc_4_fu_490_p5;
wire  signed [1:0] yloc_4_fu_490_p7;
wire   [1:0] Rloc_19_fu_514_p1;
wire   [1:0] Rloc_19_fu_514_p3;
wire  signed [1:0] Rloc_19_fu_514_p5;
wire  signed [1:0] Rloc_19_fu_514_p7;
wire   [1:0] Rloc_16_fu_538_p1;
wire   [1:0] Rloc_16_fu_538_p3;
wire  signed [1:0] Rloc_16_fu_538_p5;
wire  signed [1:0] Rloc_16_fu_538_p7;
wire   [1:0] Rloc_17_fu_562_p1;
wire   [1:0] Rloc_17_fu_562_p3;
wire  signed [1:0] Rloc_17_fu_562_p5;
wire  signed [1:0] Rloc_17_fu_562_p7;
wire   [1:0] Rloc_18_fu_586_p1;
wire   [1:0] Rloc_18_fu_586_p3;
wire  signed [1:0] Rloc_18_fu_586_p5;
wire  signed [1:0] Rloc_18_fu_586_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_122 = 3'd0;
#0 yloc_fu_126 = 16'd0;
#0 yloc_1_fu_130 = 16'd0;
#0 yloc_2_fu_134 = 16'd0;
#0 yloc_3_fu_138 = 16'd0;
#0 Rloc_15_fu_142 = 16'd0;
#0 Rloc_14_fu_146 = 16'd0;
#0 Rloc_13_fu_150 = 16'd0;
#0 Rloc_12_fu_154 = 16'd0;
#0 Rloc_11_fu_158 = 16'd0;
#0 Rloc_10_fu_162 = 16'd0;
#0 Rloc_9_fu_166 = 16'd0;
#0 Rloc_8_fu_170 = 16'd0;
#0 Rloc_7_fu_174 = 16'd0;
#0 Rloc_6_fu_178 = 16'd0;
#0 Rloc_5_fu_182 = 16'd0;
#0 Rloc_4_fu_186 = 16'd0;
#0 Rloc_3_fu_190 = 16'd0;
#0 Rloc_2_fu_194 = 16'd0;
#0 Rloc_1_fu_198 = 16'd0;
#0 Rloc_fu_202 = 16'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U432(
    .din0(y_in_0_val),
    .din1(y_in_1_val),
    .din2(y_in_2_val),
    .din3(y_in_3_val),
    .def(yloc_4_fu_490_p9),
    .sel(trunc_ln20_fu_486_p1),
    .dout(yloc_4_fu_490_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U433(
    .din0(p_read),
    .din1(p_read1),
    .din2(p_read2),
    .din3(p_read3),
    .def(Rloc_19_fu_514_p9),
    .sel(trunc_ln20_fu_486_p1),
    .dout(Rloc_19_fu_514_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U434(
    .din0(p_read4),
    .din1(p_read5),
    .din2(p_read6),
    .din3(p_read7),
    .def(Rloc_16_fu_538_p9),
    .sel(trunc_ln20_fu_486_p1),
    .dout(Rloc_16_fu_538_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U435(
    .din0(p_read8),
    .din1(p_read9),
    .din2(p_read10),
    .din3(p_read11),
    .def(Rloc_17_fu_562_p9),
    .sel(trunc_ln20_fu_486_p1),
    .dout(Rloc_17_fu_562_p11)
);

(* dissolve_hierarchy = "yes" *) solve_top_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U436(
    .din0(p_read12),
    .din1(p_read13),
    .din2(p_read14),
    .din3(p_read15),
    .def(Rloc_18_fu_586_p9),
    .sel(trunc_ln20_fu_486_p1),
    .dout(Rloc_18_fu_586_p11)
);

solve_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln20_fu_474_p2 == 1'd0)) begin
            i_fu_122 <= add_ln20_fu_480_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_122 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_fu_474_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln20_fu_486_p1 == 2'd2))) begin
        Rloc_10_fu_162 <= Rloc_17_fu_562_p11;
        Rloc_14_fu_146 <= Rloc_18_fu_586_p11;
        Rloc_2_fu_194 <= Rloc_19_fu_514_p11;
        Rloc_6_fu_178 <= Rloc_16_fu_538_p11;
        yloc_2_fu_134 <= yloc_4_fu_490_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_fu_474_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln20_fu_486_p1 == 2'd3))) begin
        Rloc_11_fu_158 <= Rloc_17_fu_562_p11;
        Rloc_15_fu_142 <= Rloc_18_fu_586_p11;
        Rloc_3_fu_190 <= Rloc_19_fu_514_p11;
        Rloc_7_fu_174 <= Rloc_16_fu_538_p11;
        yloc_3_fu_138 <= yloc_4_fu_490_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_fu_474_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln20_fu_486_p1 == 2'd0))) begin
        Rloc_12_fu_154 <= Rloc_18_fu_586_p11;
        Rloc_4_fu_186 <= Rloc_16_fu_538_p11;
        Rloc_8_fu_170 <= Rloc_17_fu_562_p11;
        Rloc_fu_202 <= Rloc_19_fu_514_p11;
        yloc_fu_126 <= yloc_4_fu_490_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_fu_474_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln20_fu_486_p1 == 2'd1))) begin
        Rloc_13_fu_150 <= Rloc_18_fu_586_p11;
        Rloc_1_fu_198 <= Rloc_19_fu_514_p11;
        Rloc_5_fu_182 <= Rloc_16_fu_538_p11;
        Rloc_9_fu_166 <= Rloc_17_fu_562_p11;
        yloc_1_fu_130 <= yloc_4_fu_490_p11;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_10_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_10_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_11_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_11_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_12_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_12_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_13_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_13_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_14_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_14_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_15_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_15_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_1_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_1_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_2_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_3_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_3_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_4_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_4_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_5_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_5_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_6_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_6_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_7_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_7_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_8_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_8_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_9_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_9_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Rloc_load_out_ap_vld = 1'b1;
    end else begin
        Rloc_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_2 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_122;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        yloc_1_out_ap_vld = 1'b1;
    end else begin
        yloc_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        yloc_2_out_ap_vld = 1'b1;
    end else begin
        yloc_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        yloc_3_out_ap_vld = 1'b1;
    end else begin
        yloc_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln20_fu_474_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        yloc_out_ap_vld = 1'b1;
    end else begin
        yloc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Rloc_10_load_out = Rloc_10_fu_162;

assign Rloc_11_load_out = Rloc_11_fu_158;

assign Rloc_12_load_out = Rloc_12_fu_154;

assign Rloc_13_load_out = Rloc_13_fu_150;

assign Rloc_14_load_out = Rloc_14_fu_146;

assign Rloc_15_load_out = Rloc_15_fu_142;

assign Rloc_16_fu_538_p9 = 'bx;

assign Rloc_17_fu_562_p9 = 'bx;

assign Rloc_18_fu_586_p9 = 'bx;

assign Rloc_19_fu_514_p9 = 'bx;

assign Rloc_1_load_out = Rloc_1_fu_198;

assign Rloc_2_load_out = Rloc_2_fu_194;

assign Rloc_3_load_out = Rloc_3_fu_190;

assign Rloc_4_load_out = Rloc_4_fu_186;

assign Rloc_5_load_out = Rloc_5_fu_182;

assign Rloc_6_load_out = Rloc_6_fu_178;

assign Rloc_7_load_out = Rloc_7_fu_174;

assign Rloc_8_load_out = Rloc_8_fu_170;

assign Rloc_9_load_out = Rloc_9_fu_166;

assign Rloc_load_out = Rloc_fu_202;

assign add_ln20_fu_480_p2 = (ap_sig_allocacmp_i_2 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln20_fu_474_p2 = ((ap_sig_allocacmp_i_2 == 3'd4) ? 1'b1 : 1'b0);

assign trunc_ln20_fu_486_p1 = ap_sig_allocacmp_i_2[1:0];

assign yloc_1_out = yloc_1_fu_130;

assign yloc_2_out = yloc_2_fu_134;

assign yloc_3_out = yloc_3_fu_138;

assign yloc_4_fu_490_p9 = 'bx;

assign yloc_out = yloc_fu_126;

endmodule //solve_top_upper_backsub_Pipeline_VITIS_LOOP_20_1
