# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ELEC522/sm512/asdf/Vivado/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_solve_top_0_0/design_1_solve_top_0_0.xci
# IP: The module: 'design_1_solve_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ELEC522/sm512/asdf/Vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_solve_top_0_0/hdl/ip/solve_top_fpext_32ns_64_2_no_dsp_1_ip/solve_top_fpext_32ns_64_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==solve_top_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==solve_top_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/ELEC522/sm512/asdf/Vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_solve_top_0_0/constraints/solve_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_solve_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/ELEC522/sm512/asdf/Vivado/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_solve_top_0_0/design_1_solve_top_0_0.xci
# IP: The module: 'design_1_solve_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ELEC522/sm512/asdf/Vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_solve_top_0_0/hdl/ip/solve_top_fpext_32ns_64_2_no_dsp_1_ip/solve_top_fpext_32ns_64_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==solve_top_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==solve_top_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/ELEC522/sm512/asdf/Vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_solve_top_0_0/constraints/solve_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_solve_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
