-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity solve_top_decompose_qr_Pipeline_VITIS_LOOP_18_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_aug : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_ap_vld : OUT STD_LOGIC;
    local_aug_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_4_ap_vld : OUT STD_LOGIC;
    local_aug_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_8_ap_vld : OUT STD_LOGIC;
    local_aug_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_12_ap_vld : OUT STD_LOGIC;
    local_aug_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_16_ap_vld : OUT STD_LOGIC;
    local_aug_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_20_ap_vld : OUT STD_LOGIC;
    local_aug_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_24_ap_vld : OUT STD_LOGIC;
    local_aug_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_28_ap_vld : OUT STD_LOGIC;
    local_aug_31 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_31_ap_vld : OUT STD_LOGIC;
    local_aug_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_30_ap_vld : OUT STD_LOGIC;
    local_aug_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_29_ap_vld : OUT STD_LOGIC;
    local_aug_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_27_ap_vld : OUT STD_LOGIC;
    local_aug_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_26_ap_vld : OUT STD_LOGIC;
    local_aug_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_25_ap_vld : OUT STD_LOGIC;
    local_aug_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_23_ap_vld : OUT STD_LOGIC;
    local_aug_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_22_ap_vld : OUT STD_LOGIC;
    local_aug_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_21_ap_vld : OUT STD_LOGIC;
    local_aug_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_19_ap_vld : OUT STD_LOGIC;
    local_aug_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_18_ap_vld : OUT STD_LOGIC;
    local_aug_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_17_ap_vld : OUT STD_LOGIC;
    local_aug_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_15_ap_vld : OUT STD_LOGIC;
    local_aug_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_14_ap_vld : OUT STD_LOGIC;
    local_aug_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_13_ap_vld : OUT STD_LOGIC;
    local_aug_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_11_ap_vld : OUT STD_LOGIC;
    local_aug_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_10_ap_vld : OUT STD_LOGIC;
    local_aug_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_9_ap_vld : OUT STD_LOGIC;
    local_aug_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_7_ap_vld : OUT STD_LOGIC;
    local_aug_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_6_ap_vld : OUT STD_LOGIC;
    local_aug_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_5_ap_vld : OUT STD_LOGIC;
    local_aug_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_3_ap_vld : OUT STD_LOGIC;
    local_aug_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_2_ap_vld : OUT STD_LOGIC;
    local_aug_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_1_ap_vld : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of solve_top_decompose_qr_Pipeline_VITIS_LOOP_18_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln18_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal r_fu_144 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln18_fu_482_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_r_2 : STD_LOGIC_VECTOR (2 downto 0);
    signal local_aug_35_fu_492_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln18_fu_488_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_32_fu_520_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_33_fu_548_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_34_fu_576_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_37_cast_cast_fu_628_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_39_cast_cast_fu_660_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_49_cast_cast_fu_692_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln20_fu_724_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_35_fu_492_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_32_fu_520_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_33_fu_548_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_34_fu_576_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_36_fu_604_p9 : STD_LOGIC_VECTOR (11 downto 0);
    signal local_aug_36_fu_604_p11 : STD_LOGIC_VECTOR (11 downto 0);
    signal local_aug_37_fu_636_p9 : STD_LOGIC_VECTOR (11 downto 0);
    signal local_aug_37_fu_636_p11 : STD_LOGIC_VECTOR (11 downto 0);
    signal local_aug_38_fu_668_p9 : STD_LOGIC_VECTOR (11 downto 0);
    signal local_aug_38_fu_668_p11 : STD_LOGIC_VECTOR (11 downto 0);
    signal local_aug_39_fu_700_p9 : STD_LOGIC_VECTOR (11 downto 0);
    signal local_aug_39_fu_700_p11 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal local_aug_35_fu_492_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_35_fu_492_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_35_fu_492_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_35_fu_492_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_32_fu_520_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_32_fu_520_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_32_fu_520_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_32_fu_520_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_33_fu_548_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_33_fu_548_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_33_fu_548_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_33_fu_548_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_34_fu_576_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_34_fu_576_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_34_fu_576_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_34_fu_576_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_36_fu_604_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_36_fu_604_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_36_fu_604_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_36_fu_604_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_37_fu_636_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_37_fu_636_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_37_fu_636_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_37_fu_636_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_38_fu_668_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_38_fu_668_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_38_fu_668_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_38_fu_668_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_39_fu_700_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_39_fu_700_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_39_fu_700_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_aug_39_fu_700_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component solve_top_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component solve_top_sparsemux_9_2_12_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        din3 : IN STD_LOGIC_VECTOR (11 downto 0);
        def : IN STD_LOGIC_VECTOR (11 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component solve_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_16_1_1_U1 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => p_read,
        din1 => p_read1,
        din2 => p_read2,
        din3 => p_read3,
        def => local_aug_35_fu_492_p9,
        sel => trunc_ln18_fu_488_p1,
        dout => local_aug_35_fu_492_p11);

    sparsemux_9_2_16_1_1_U2 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => p_read4,
        din1 => p_read5,
        din2 => p_read6,
        din3 => p_read7,
        def => local_aug_32_fu_520_p9,
        sel => trunc_ln18_fu_488_p1,
        dout => local_aug_32_fu_520_p11);

    sparsemux_9_2_16_1_1_U3 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => p_read8,
        din1 => p_read9,
        din2 => p_read10,
        din3 => p_read11,
        def => local_aug_33_fu_548_p9,
        sel => trunc_ln18_fu_488_p1,
        dout => local_aug_33_fu_548_p11);

    sparsemux_9_2_16_1_1_U4 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => p_read12,
        din1 => p_read13,
        din2 => p_read14,
        din3 => p_read15,
        def => local_aug_34_fu_576_p9,
        sel => trunc_ln18_fu_488_p1,
        dout => local_aug_34_fu_576_p11);

    sparsemux_9_2_12_1_1_U5 : component solve_top_sparsemux_9_2_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 12,
        CASE1 => "01",
        din1_WIDTH => 12,
        CASE2 => "10",
        din2_WIDTH => 12,
        CASE3 => "11",
        din3_WIDTH => 12,
        def_WIDTH => 12,
        sel_WIDTH => 2,
        dout_WIDTH => 12)
    port map (
        din0 => ap_const_lv12_800,
        din1 => ap_const_lv12_0,
        din2 => ap_const_lv12_0,
        din3 => ap_const_lv12_0,
        def => local_aug_36_fu_604_p9,
        sel => trunc_ln18_fu_488_p1,
        dout => local_aug_36_fu_604_p11);

    sparsemux_9_2_12_1_1_U6 : component solve_top_sparsemux_9_2_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 12,
        CASE1 => "01",
        din1_WIDTH => 12,
        CASE2 => "10",
        din2_WIDTH => 12,
        CASE3 => "11",
        din3_WIDTH => 12,
        def_WIDTH => 12,
        sel_WIDTH => 2,
        dout_WIDTH => 12)
    port map (
        din0 => ap_const_lv12_0,
        din1 => ap_const_lv12_800,
        din2 => ap_const_lv12_0,
        din3 => ap_const_lv12_0,
        def => local_aug_37_fu_636_p9,
        sel => trunc_ln18_fu_488_p1,
        dout => local_aug_37_fu_636_p11);

    sparsemux_9_2_12_1_1_U7 : component solve_top_sparsemux_9_2_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 12,
        CASE1 => "01",
        din1_WIDTH => 12,
        CASE2 => "10",
        din2_WIDTH => 12,
        CASE3 => "11",
        din3_WIDTH => 12,
        def_WIDTH => 12,
        sel_WIDTH => 2,
        dout_WIDTH => 12)
    port map (
        din0 => ap_const_lv12_0,
        din1 => ap_const_lv12_0,
        din2 => ap_const_lv12_800,
        din3 => ap_const_lv12_0,
        def => local_aug_38_fu_668_p9,
        sel => trunc_ln18_fu_488_p1,
        dout => local_aug_38_fu_668_p11);

    sparsemux_9_2_12_1_1_U8 : component solve_top_sparsemux_9_2_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 12,
        CASE1 => "01",
        din1_WIDTH => 12,
        CASE2 => "10",
        din2_WIDTH => 12,
        CASE3 => "11",
        din3_WIDTH => 12,
        def_WIDTH => 12,
        sel_WIDTH => 2,
        dout_WIDTH => 12)
    port map (
        din0 => ap_const_lv12_0,
        din1 => ap_const_lv12_0,
        din2 => ap_const_lv12_0,
        din3 => ap_const_lv12_800,
        def => local_aug_39_fu_700_p9,
        sel => trunc_ln18_fu_488_p1,
        dout => local_aug_39_fu_700_p11);

    flow_control_loop_pipe_sequential_init_U : component solve_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    r_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln18_fu_476_p2 = ap_const_lv1_0)) then 
                    r_fu_144 <= add_ln18_fu_482_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_144 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln18_fu_482_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_r_2) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_r_2_assign_proc : process(ap_CS_fsm_state1, r_fu_144, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_r_2 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_r_2 <= r_fu_144;
        end if; 
    end process;

    icmp_ln18_fu_476_p2 <= "1" when (ap_sig_allocacmp_r_2 = ap_const_lv3_4) else "0";
    local_aug <= local_aug_35_fu_492_p11;
    local_aug_1 <= local_aug_35_fu_492_p11;
    local_aug_10 <= local_aug_33_fu_548_p11;

    local_aug_10_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_2))) then 
            local_aug_10_ap_vld <= ap_const_logic_1;
        else 
            local_aug_10_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_11 <= local_aug_33_fu_548_p11;

    local_aug_11_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_3))) then 
            local_aug_11_ap_vld <= ap_const_logic_1;
        else 
            local_aug_11_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_12 <= local_aug_34_fu_576_p11;

    local_aug_12_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_0))) then 
            local_aug_12_ap_vld <= ap_const_logic_1;
        else 
            local_aug_12_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_13 <= local_aug_34_fu_576_p11;

    local_aug_13_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_1))) then 
            local_aug_13_ap_vld <= ap_const_logic_1;
        else 
            local_aug_13_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_14 <= local_aug_34_fu_576_p11;

    local_aug_14_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_2))) then 
            local_aug_14_ap_vld <= ap_const_logic_1;
        else 
            local_aug_14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_15 <= local_aug_34_fu_576_p11;

    local_aug_15_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_3))) then 
            local_aug_15_ap_vld <= ap_const_logic_1;
        else 
            local_aug_15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_16 <= local_aug_37_cast_cast_fu_628_p1;

    local_aug_16_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_0))) then 
            local_aug_16_ap_vld <= ap_const_logic_1;
        else 
            local_aug_16_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_17 <= local_aug_37_cast_cast_fu_628_p1;

    local_aug_17_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_1))) then 
            local_aug_17_ap_vld <= ap_const_logic_1;
        else 
            local_aug_17_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_18 <= local_aug_37_cast_cast_fu_628_p1;

    local_aug_18_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_2))) then 
            local_aug_18_ap_vld <= ap_const_logic_1;
        else 
            local_aug_18_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_19 <= local_aug_37_cast_cast_fu_628_p1;

    local_aug_19_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_3))) then 
            local_aug_19_ap_vld <= ap_const_logic_1;
        else 
            local_aug_19_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    local_aug_1_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_1))) then 
            local_aug_1_ap_vld <= ap_const_logic_1;
        else 
            local_aug_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_2 <= local_aug_35_fu_492_p11;
    local_aug_20 <= local_aug_39_cast_cast_fu_660_p1;

    local_aug_20_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_0))) then 
            local_aug_20_ap_vld <= ap_const_logic_1;
        else 
            local_aug_20_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_21 <= local_aug_39_cast_cast_fu_660_p1;

    local_aug_21_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_1))) then 
            local_aug_21_ap_vld <= ap_const_logic_1;
        else 
            local_aug_21_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_22 <= local_aug_39_cast_cast_fu_660_p1;

    local_aug_22_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_2))) then 
            local_aug_22_ap_vld <= ap_const_logic_1;
        else 
            local_aug_22_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_23 <= local_aug_39_cast_cast_fu_660_p1;

    local_aug_23_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_3))) then 
            local_aug_23_ap_vld <= ap_const_logic_1;
        else 
            local_aug_23_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_24 <= local_aug_49_cast_cast_fu_692_p1;

    local_aug_24_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_0))) then 
            local_aug_24_ap_vld <= ap_const_logic_1;
        else 
            local_aug_24_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_25 <= local_aug_49_cast_cast_fu_692_p1;

    local_aug_25_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_1))) then 
            local_aug_25_ap_vld <= ap_const_logic_1;
        else 
            local_aug_25_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_26 <= local_aug_49_cast_cast_fu_692_p1;

    local_aug_26_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_2))) then 
            local_aug_26_ap_vld <= ap_const_logic_1;
        else 
            local_aug_26_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_27 <= local_aug_49_cast_cast_fu_692_p1;

    local_aug_27_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_3))) then 
            local_aug_27_ap_vld <= ap_const_logic_1;
        else 
            local_aug_27_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_28 <= zext_ln20_fu_724_p1;

    local_aug_28_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_0))) then 
            local_aug_28_ap_vld <= ap_const_logic_1;
        else 
            local_aug_28_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_29 <= zext_ln20_fu_724_p1;

    local_aug_29_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_1))) then 
            local_aug_29_ap_vld <= ap_const_logic_1;
        else 
            local_aug_29_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    local_aug_2_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_2))) then 
            local_aug_2_ap_vld <= ap_const_logic_1;
        else 
            local_aug_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_3 <= local_aug_35_fu_492_p11;
    local_aug_30 <= zext_ln20_fu_724_p1;

    local_aug_30_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_2))) then 
            local_aug_30_ap_vld <= ap_const_logic_1;
        else 
            local_aug_30_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_31 <= zext_ln20_fu_724_p1;

    local_aug_31_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_3))) then 
            local_aug_31_ap_vld <= ap_const_logic_1;
        else 
            local_aug_31_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_32_fu_520_p9 <= "XXXXXXXXXXXXXXXX";
    local_aug_33_fu_548_p9 <= "XXXXXXXXXXXXXXXX";
    local_aug_34_fu_576_p9 <= "XXXXXXXXXXXXXXXX";
    local_aug_35_fu_492_p9 <= "XXXXXXXXXXXXXXXX";
    local_aug_36_fu_604_p9 <= "XXXXXXXXXXXX";
    local_aug_37_cast_cast_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(local_aug_36_fu_604_p11),16));
    local_aug_37_fu_636_p9 <= "XXXXXXXXXXXX";
    local_aug_38_fu_668_p9 <= "XXXXXXXXXXXX";
    local_aug_39_cast_cast_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(local_aug_37_fu_636_p11),16));
    local_aug_39_fu_700_p9 <= "XXXXXXXXXXXX";

    local_aug_3_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_3))) then 
            local_aug_3_ap_vld <= ap_const_logic_1;
        else 
            local_aug_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_4 <= local_aug_32_fu_520_p11;
    local_aug_49_cast_cast_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(local_aug_38_fu_668_p11),16));

    local_aug_4_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_0))) then 
            local_aug_4_ap_vld <= ap_const_logic_1;
        else 
            local_aug_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_5 <= local_aug_32_fu_520_p11;

    local_aug_5_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_1))) then 
            local_aug_5_ap_vld <= ap_const_logic_1;
        else 
            local_aug_5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_6 <= local_aug_32_fu_520_p11;

    local_aug_6_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_2))) then 
            local_aug_6_ap_vld <= ap_const_logic_1;
        else 
            local_aug_6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_7 <= local_aug_32_fu_520_p11;

    local_aug_7_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_3))) then 
            local_aug_7_ap_vld <= ap_const_logic_1;
        else 
            local_aug_7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_8 <= local_aug_33_fu_548_p11;

    local_aug_8_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_0))) then 
            local_aug_8_ap_vld <= ap_const_logic_1;
        else 
            local_aug_8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_9 <= local_aug_33_fu_548_p11;

    local_aug_9_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_1))) then 
            local_aug_9_ap_vld <= ap_const_logic_1;
        else 
            local_aug_9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    local_aug_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln18_fu_476_p2, trunc_ln18_fu_488_p1)
    begin
        if (((icmp_ln18_fu_476_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln18_fu_488_p1 = ap_const_lv2_0))) then 
            local_aug_ap_vld <= ap_const_logic_1;
        else 
            local_aug_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln18_fu_488_p1 <= ap_sig_allocacmp_r_2(2 - 1 downto 0);
    zext_ln20_fu_724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(local_aug_39_fu_700_p11),16));
end behav;
