-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity solve_top_decompose_qr_Pipeline_VITIS_LOOP_63_7 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tmp_217 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_216 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_215 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_214 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_202 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_201 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_200 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_199 : IN STD_LOGIC_VECTOR (15 downto 0);
    local_aug_47_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_47_out_ap_vld : OUT STD_LOGIC;
    local_aug_46_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_46_out_ap_vld : OUT STD_LOGIC;
    local_aug_45_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_45_out_ap_vld : OUT STD_LOGIC;
    local_aug_44_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_44_out_ap_vld : OUT STD_LOGIC;
    local_aug_43_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_43_out_ap_vld : OUT STD_LOGIC;
    local_aug_42_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_42_out_ap_vld : OUT STD_LOGIC;
    local_aug_41_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_41_out_ap_vld : OUT STD_LOGIC;
    local_aug_40_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_aug_40_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of solve_top_decompose_qr_Pipeline_VITIS_LOOP_63_7 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln63_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal trunc_ln63_fu_294_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln63_reg_594 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal c_fu_94 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln63_fu_288_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal local_aug_40_fu_98 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln64_1_fu_440_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_aug_41_fu_102 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal local_aug_42_fu_106 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal local_aug_43_fu_110 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal local_aug_44_fu_114 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal local_aug_45_fu_118 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal local_aug_46_fu_122 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal local_aug_47_fu_126 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_s_fu_345_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_345_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln64_fu_384_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln64_fu_388_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_394_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_229_fu_406_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln64_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln64_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln64_1_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln64_fu_432_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln64_fu_402_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_s_fu_345_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_345_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_345_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_345_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_345_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_345_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_345_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_345_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component solve_top_sparsemux_17_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (15 downto 0);
        din6 : IN STD_LOGIC_VECTOR (15 downto 0);
        din7 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component solve_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_17_3_16_1_1_U159 : component solve_top_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => local_aug_40_fu_98,
        din1 => local_aug_41_fu_102,
        din2 => local_aug_42_fu_106,
        din3 => local_aug_43_fu_110,
        din4 => local_aug_44_fu_114,
        din5 => local_aug_45_fu_118,
        din6 => local_aug_46_fu_122,
        din7 => local_aug_47_fu_126,
        def => tmp_s_fu_345_p17,
        sel => trunc_ln63_reg_594,
        dout => tmp_s_fu_345_p19);

    flow_control_loop_pipe_sequential_init_U : component solve_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    c_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln63_fu_282_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_94 <= add_ln63_fu_288_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_94 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    local_aug_40_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    local_aug_40_fu_98 <= tmp_199;
                elsif (((trunc_ln63_reg_594 = ap_const_lv3_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    local_aug_40_fu_98 <= select_ln64_1_fu_440_p3;
                end if;
            end if; 
        end if;
    end process;

    local_aug_41_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    local_aug_41_fu_102 <= tmp_200;
                elsif (((trunc_ln63_reg_594 = ap_const_lv3_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    local_aug_41_fu_102 <= select_ln64_1_fu_440_p3;
                end if;
            end if; 
        end if;
    end process;

    local_aug_42_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    local_aug_42_fu_106 <= tmp_201;
                elsif (((trunc_ln63_reg_594 = ap_const_lv3_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    local_aug_42_fu_106 <= select_ln64_1_fu_440_p3;
                end if;
            end if; 
        end if;
    end process;

    local_aug_43_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    local_aug_43_fu_110 <= tmp_202;
                elsif (((trunc_ln63_reg_594 = ap_const_lv3_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    local_aug_43_fu_110 <= select_ln64_1_fu_440_p3;
                end if;
            end if; 
        end if;
    end process;

    local_aug_44_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    local_aug_44_fu_114 <= tmp_214;
                elsif (((trunc_ln63_reg_594 = ap_const_lv3_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    local_aug_44_fu_114 <= select_ln64_1_fu_440_p3;
                end if;
            end if; 
        end if;
    end process;

    local_aug_45_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    local_aug_45_fu_118 <= tmp_215;
                elsif (((trunc_ln63_reg_594 = ap_const_lv3_5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    local_aug_45_fu_118 <= select_ln64_1_fu_440_p3;
                end if;
            end if; 
        end if;
    end process;

    local_aug_46_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    local_aug_46_fu_122 <= tmp_216;
                elsif (((trunc_ln63_reg_594 = ap_const_lv3_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    local_aug_46_fu_122 <= select_ln64_1_fu_440_p3;
                end if;
            end if; 
        end if;
    end process;

    local_aug_47_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    local_aug_47_fu_126 <= tmp_217;
                elsif (((trunc_ln63_reg_594 = ap_const_lv3_7) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    local_aug_47_fu_126 <= select_ln64_1_fu_440_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln63_reg_594 <= trunc_ln63_fu_294_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln63_fu_288_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_1) + unsigned(ap_const_lv4_1));
    and_ln64_fu_420_p2 <= (xor_ln64_fu_414_p2 and tmp_229_fu_406_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln63_fu_282_p2)
    begin
        if (((icmp_ln63_fu_282_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_1_assign_proc : process(ap_CS_fsm_pp0_stage0, c_fu_94, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_c_1 <= c_fu_94;
        end if; 
    end process;

    icmp_ln63_fu_282_p2 <= "1" when (ap_sig_allocacmp_c_1 = ap_const_lv4_8) else "0";
    local_aug_40_out <= local_aug_40_fu_98;

    local_aug_40_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln63_fu_282_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln63_fu_282_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_aug_40_out_ap_vld <= ap_const_logic_1;
        else 
            local_aug_40_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_41_out <= local_aug_41_fu_102;

    local_aug_41_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln63_fu_282_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln63_fu_282_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_aug_41_out_ap_vld <= ap_const_logic_1;
        else 
            local_aug_41_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_42_out <= local_aug_42_fu_106;

    local_aug_42_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln63_fu_282_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln63_fu_282_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_aug_42_out_ap_vld <= ap_const_logic_1;
        else 
            local_aug_42_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_43_out <= local_aug_43_fu_110;

    local_aug_43_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln63_fu_282_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln63_fu_282_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_aug_43_out_ap_vld <= ap_const_logic_1;
        else 
            local_aug_43_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_44_out <= local_aug_44_fu_114;

    local_aug_44_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln63_fu_282_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln63_fu_282_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_aug_44_out_ap_vld <= ap_const_logic_1;
        else 
            local_aug_44_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_45_out <= local_aug_45_fu_118;

    local_aug_45_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln63_fu_282_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln63_fu_282_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_aug_45_out_ap_vld <= ap_const_logic_1;
        else 
            local_aug_45_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_46_out <= local_aug_46_fu_122;

    local_aug_46_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln63_fu_282_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln63_fu_282_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_aug_46_out_ap_vld <= ap_const_logic_1;
        else 
            local_aug_46_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    local_aug_47_out <= local_aug_47_fu_126;

    local_aug_47_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln63_fu_282_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln63_fu_282_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_aug_47_out_ap_vld <= ap_const_logic_1;
        else 
            local_aug_47_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln64_1_fu_440_p3 <= 
        select_ln64_fu_432_p3 when (xor_ln64_1_fu_426_p2(0) = '1') else 
        trunc_ln64_fu_402_p1;
    select_ln64_fu_432_p3 <= 
        ap_const_lv16_7FFF when (and_ln64_fu_420_p2(0) = '1') else 
        ap_const_lv16_8000;
        sext_ln64_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_345_p19),17));

    sub_ln64_fu_388_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln64_fu_384_p1));
    tmp_229_fu_406_p3 <= sub_ln64_fu_388_p2(15 downto 15);
    tmp_fu_394_p3 <= sub_ln64_fu_388_p2(16 downto 16);
    tmp_s_fu_345_p17 <= "XXXXXXXXXXXXXXXX";
    trunc_ln63_fu_294_p1 <= ap_sig_allocacmp_c_1(3 - 1 downto 0);
    trunc_ln64_fu_402_p1 <= sub_ln64_fu_388_p2(16 - 1 downto 0);
    xor_ln64_1_fu_426_p2 <= (tmp_fu_394_p3 xor tmp_229_fu_406_p3);
    xor_ln64_fu_414_p2 <= (tmp_fu_394_p3 xor ap_const_lv1_1);
end behav;
