-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_40_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mat_local_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_1_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_2_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_3_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv7_i : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_4_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_5_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_6_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_7_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv7_i_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_8_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_9_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_10_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_11_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv7_i_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_12_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_13_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_14_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    mat_local_15_load_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv7_i_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    res_local_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_local_3_out_ap_vld : OUT STD_LOGIC;
    res_local_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_local_2_out_ap_vld : OUT STD_LOGIC;
    res_local_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_local_1_out_ap_vld : OUT STD_LOGIC;
    res_local_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_local_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of solve_top_mat_vec_mul_Pipeline_VITIS_LOOP_40_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln40_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal conv7_i_3_cast_fu_296_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_i_3_cast_reg_1473 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_i_2_cast_fu_300_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_i_2_cast_reg_1478 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_i_1_cast_fu_304_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_i_1_cast_reg_1483 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_i_cast_fu_308_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_i_cast_reg_1488 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln40_reg_1493 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_reg_1493_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_reg_1493_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_reg_1493_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_fu_352_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln40_reg_1497 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln40_reg_1497_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln40_reg_1497_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln40_reg_1497_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln40_reg_1497_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_356_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_1504 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln44_fu_398_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln44_reg_1509 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_209_reg_1515 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_1_fu_433_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_1_reg_1521 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_212_reg_1526 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_reg_1533 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_240_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_240_reg_1538 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_241_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_241_reg_1545 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln44_1_fu_508_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln44_1_reg_1550 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_215_reg_1555 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln44_fu_652_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_reg_1560 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_214_reg_1566 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_3_fu_678_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_3_reg_1572 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_217_reg_1577 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_242_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_242_reg_1584 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_243_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_243_reg_1589 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_244_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_244_reg_1596 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln44_2_fu_753_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln44_2_reg_1601 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_220_reg_1606 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln44_114_fu_897_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_114_reg_1611 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_219_reg_1617 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_5_fu_923_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_5_reg_1623 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_222_reg_1628 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_245_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_245_reg_1635 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_246_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_246_reg_1640 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_247_fu_969_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_247_reg_1647 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln44_3_fu_998_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln44_3_reg_1652 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_225_reg_1657 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_225_reg_1657_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln44_116_fu_1142_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_116_reg_1662 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_224_reg_1668 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_6_reg_1674 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln44_248_fu_1175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_248_reg_1679 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_249_fu_1191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_249_reg_1684 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_250_fu_1197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_250_reg_1691 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_3_fu_128 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln40_fu_346_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal res_local_fu_132 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal sum_9_fu_1334_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal res_local_1_fu_136 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal res_local_2_fu_140 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal res_local_3_fu_144 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_356_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_356_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln44_fu_398_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_210_fu_421_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_fu_411_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln44_fu_429_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_447_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_170_fu_463_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_171_fu_485_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_171_fu_485_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln44_1_fu_508_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_211_fu_521_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_fu_533_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_213_fu_539_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_128_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_160_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_fu_546_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_130_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_131_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_96_fu_563_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_161_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_164_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_71_fu_602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_144_fu_608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_163_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_165_fu_614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_64_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_112_fu_625_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln44_113_fu_633_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_640_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln44_33_fu_648_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_2_fu_665_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln44_96_fu_675_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_fu_692_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_708_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_172_fu_730_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_172_fu_730_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln44_2_fu_753_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_216_fu_766_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_133_fu_773_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_166_fu_778_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_218_fu_784_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_134_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_167_fu_803_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_99_fu_791_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_136_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_65_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_137_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_100_fu_808_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_168_fu_815_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_171_fu_842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_72_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_147_fu_853_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_170_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_172_fu_859_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_66_fu_864_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_114_fu_870_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln44_115_fu_878_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln44_s_fu_885_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln44_35_fu_893_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_4_fu_910_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln44_97_fu_920_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_14_fu_937_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_15_fu_953_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_173_fu_975_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_173_fu_975_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln44_3_fu_998_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_221_fu_1011_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_139_fu_1018_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_173_fu_1023_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_223_fu_1029_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_140_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_174_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_103_fu_1036_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_142_fu_1065_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_67_fu_1071_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_143_fu_1076_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_104_fu_1053_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_175_fu_1060_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_178_fu_1087_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_73_fu_1092_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_150_fu_1098_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_177_fu_1081_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_179_fu_1104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_68_fu_1109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_116_fu_1115_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln44_117_fu_1123_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln44_1_fu_1130_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln44_37_fu_1138_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_1165_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_17_fu_1181_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln44_98_fu_1210_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_7_fu_1213_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_227_fu_1218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_226_fu_1203_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_145_fu_1226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_180_fu_1232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_228_fu_1238_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_146_fu_1251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_181_fu_1257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_107_fu_1245_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_148_fu_1274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_69_fu_1280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_149_fu_1286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_108_fu_1262_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_182_fu_1269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_185_fu_1297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_74_fu_1303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_151_fu_1309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_184_fu_1291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_186_fu_1315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_70_fu_1328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_109_fu_1320_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_356_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_356_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_356_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_356_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_171_fu_485_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_171_fu_485_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_171_fu_485_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_171_fu_485_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_172_fu_730_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_172_fu_730_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_172_fu_730_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_172_fu_730_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_173_fu_975_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_173_fu_975_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_173_fu_975_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_173_fu_975_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component solve_top_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component solve_top_mul_16s_16s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component solve_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_16_1_1_U366 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => mat_local_load_reload,
        din1 => mat_local_1_load_reload,
        din2 => mat_local_2_load_reload,
        din3 => mat_local_3_load_reload,
        def => tmp_fu_356_p9,
        sel => tmp_fu_356_p10,
        dout => tmp_fu_356_p11);

    mul_16s_16s_32_1_1_U367 : component solve_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_reg_1504,
        din1 => mul_ln44_fu_398_p1,
        dout => mul_ln44_fu_398_p2);

    sparsemux_9_2_16_1_1_U368 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => mat_local_4_load_reload,
        din1 => mat_local_5_load_reload,
        din2 => mat_local_6_load_reload,
        din3 => mat_local_7_load_reload,
        def => tmp_171_fu_485_p9,
        sel => trunc_ln40_reg_1497,
        dout => tmp_171_fu_485_p11);

    mul_16s_16s_32_1_1_U369 : component solve_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_171_fu_485_p11,
        din1 => mul_ln44_1_fu_508_p1,
        dout => mul_ln44_1_fu_508_p2);

    sparsemux_9_2_16_1_1_U370 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => mat_local_8_load_reload,
        din1 => mat_local_9_load_reload,
        din2 => mat_local_10_load_reload,
        din3 => mat_local_11_load_reload,
        def => tmp_172_fu_730_p9,
        sel => trunc_ln40_reg_1497_pp0_iter1_reg,
        dout => tmp_172_fu_730_p11);

    mul_16s_16s_32_1_1_U371 : component solve_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_172_fu_730_p11,
        din1 => mul_ln44_2_fu_753_p1,
        dout => mul_ln44_2_fu_753_p2);

    sparsemux_9_2_16_1_1_U372 : component solve_top_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => mat_local_12_load_reload,
        din1 => mat_local_13_load_reload,
        din2 => mat_local_14_load_reload,
        din3 => mat_local_15_load_reload,
        def => tmp_173_fu_975_p9,
        sel => trunc_ln40_reg_1497_pp0_iter2_reg,
        dout => tmp_173_fu_975_p11);

    mul_16s_16s_32_1_1_U373 : component solve_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_173_fu_975_p11,
        din1 => mul_ln44_3_fu_998_p1,
        dout => mul_ln44_3_fu_998_p2);

    flow_control_loop_pipe_sequential_init_U : component solve_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    i_3_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln40_fu_340_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_3_fu_128 <= add_ln40_fu_346_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_3_fu_128 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    res_local_1_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    res_local_1_fu_136 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln40_reg_1497_pp0_iter4_reg = ap_const_lv2_1))) then 
                    res_local_1_fu_136 <= sum_9_fu_1334_p3;
                end if;
            end if; 
        end if;
    end process;

    res_local_2_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    res_local_2_fu_140 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln40_reg_1497_pp0_iter4_reg = ap_const_lv2_2))) then 
                    res_local_2_fu_140 <= sum_9_fu_1334_p3;
                end if;
            end if; 
        end if;
    end process;

    res_local_3_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    res_local_3_fu_144 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln40_reg_1497_pp0_iter4_reg = ap_const_lv2_3))) then 
                    res_local_3_fu_144 <= sum_9_fu_1334_p3;
                end if;
            end if; 
        end if;
    end process;

    res_local_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    res_local_fu_132 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln40_reg_1497_pp0_iter4_reg = ap_const_lv2_0))) then 
                    res_local_fu_132 <= sum_9_fu_1334_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln44_114_reg_1611 <= add_ln44_114_fu_897_p2;
                add_ln44_116_reg_1662 <= add_ln44_116_fu_1142_p2;
                add_ln44_reg_1560 <= add_ln44_fu_652_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln40_reg_1493_pp0_iter2_reg <= icmp_ln40_reg_1493_pp0_iter1_reg;
                icmp_ln40_reg_1493_pp0_iter3_reg <= icmp_ln40_reg_1493_pp0_iter2_reg;
                icmp_ln44_242_reg_1584 <= icmp_ln44_242_fu_702_p2;
                icmp_ln44_243_reg_1589 <= icmp_ln44_243_fu_718_p2;
                icmp_ln44_244_reg_1596 <= icmp_ln44_244_fu_724_p2;
                icmp_ln44_245_reg_1635 <= icmp_ln44_245_fu_947_p2;
                icmp_ln44_246_reg_1640 <= icmp_ln44_246_fu_963_p2;
                icmp_ln44_247_reg_1647 <= icmp_ln44_247_fu_969_p2;
                icmp_ln44_248_reg_1679 <= icmp_ln44_248_fu_1175_p2;
                icmp_ln44_249_reg_1684 <= icmp_ln44_249_fu_1191_p2;
                icmp_ln44_250_reg_1691 <= icmp_ln44_250_fu_1197_p2;
                mul_ln44_2_reg_1601 <= mul_ln44_2_fu_753_p2;
                mul_ln44_3_reg_1652 <= mul_ln44_3_fu_998_p2;
                sum_3_reg_1572 <= sum_3_fu_678_p2;
                sum_5_reg_1623 <= sum_5_fu_923_p2;
                sum_6_reg_1674 <= add_ln44_116_fu_1142_p2(26 downto 11);
                tmp_214_reg_1566 <= add_ln44_fu_652_p2(31 downto 31);
                tmp_217_reg_1577 <= sum_3_fu_678_p2(15 downto 15);
                tmp_219_reg_1617 <= add_ln44_114_fu_897_p2(31 downto 31);
                tmp_220_reg_1606 <= mul_ln44_2_fu_753_p2(10 downto 10);
                tmp_222_reg_1628 <= sum_5_fu_923_p2(15 downto 15);
                tmp_224_reg_1668 <= add_ln44_116_fu_1142_p2(31 downto 31);
                tmp_225_reg_1657 <= mul_ln44_3_fu_998_p2(10 downto 10);
                tmp_225_reg_1657_pp0_iter4_reg <= tmp_225_reg_1657;
                trunc_ln40_reg_1497_pp0_iter2_reg <= trunc_ln40_reg_1497_pp0_iter1_reg;
                trunc_ln40_reg_1497_pp0_iter3_reg <= trunc_ln40_reg_1497_pp0_iter2_reg;
                trunc_ln40_reg_1497_pp0_iter4_reg <= trunc_ln40_reg_1497_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                conv7_i_1_cast_reg_1483 <= conv7_i_1_cast_fu_304_p1;
                conv7_i_2_cast_reg_1478 <= conv7_i_2_cast_fu_300_p1;
                conv7_i_3_cast_reg_1473 <= conv7_i_3_cast_fu_296_p1;
                conv7_i_cast_reg_1488 <= conv7_i_cast_fu_308_p1;
                icmp_ln40_reg_1493 <= icmp_ln40_fu_340_p2;
                icmp_ln40_reg_1493_pp0_iter1_reg <= icmp_ln40_reg_1493;
                icmp_ln44_240_reg_1538 <= icmp_ln44_240_fu_473_p2;
                icmp_ln44_241_reg_1545 <= icmp_ln44_241_fu_479_p2;
                icmp_ln44_reg_1533 <= icmp_ln44_fu_457_p2;
                mul_ln44_1_reg_1550 <= mul_ln44_1_fu_508_p2;
                mul_ln44_reg_1509 <= mul_ln44_fu_398_p2;
                sum_1_reg_1521 <= sum_1_fu_433_p2;
                tmp_209_reg_1515 <= mul_ln44_fu_398_p2(31 downto 31);
                tmp_212_reg_1526 <= sum_1_fu_433_p2(15 downto 15);
                tmp_215_reg_1555 <= mul_ln44_1_fu_508_p2(10 downto 10);
                tmp_reg_1504 <= tmp_fu_356_p11;
                trunc_ln40_reg_1497 <= trunc_ln40_fu_352_p1;
                trunc_ln40_reg_1497_pp0_iter1_reg <= trunc_ln40_reg_1497;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln40_fu_346_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv3_1));
    add_ln44_114_fu_897_p2 <= std_logic_vector(signed(sext_ln44_35_fu_893_p1) + signed(mul_ln44_2_reg_1601));
    add_ln44_116_fu_1142_p2 <= std_logic_vector(signed(sext_ln44_37_fu_1138_p1) + signed(mul_ln44_3_reg_1652));
    add_ln44_fu_652_p2 <= std_logic_vector(signed(sext_ln44_33_fu_648_p1) + signed(mul_ln44_1_reg_1550));
    and_ln44_160_fu_558_p2 <= (xor_ln44_128_fu_552_p2 and icmp_ln44_reg_1533);
    and_ln44_161_fu_570_p2 <= (icmp_ln44_240_reg_1538 and and_ln44_fu_533_p2);
    and_ln44_163_fu_591_p2 <= (xor_ln44_131_fu_586_p2 and or_ln44_fu_581_p2);
    and_ln44_164_fu_597_p2 <= (tmp_212_reg_1526 and select_ln44_96_fu_563_p3);
    and_ln44_165_fu_614_p2 <= (xor_ln44_144_fu_608_p2 and tmp_209_reg_1515);
    and_ln44_166_fu_778_p2 <= (xor_ln44_133_fu_773_p2 and tmp_216_fu_766_p3);
    and_ln44_167_fu_803_p2 <= (xor_ln44_134_fu_797_p2 and icmp_ln44_242_reg_1584);
    and_ln44_168_fu_815_p2 <= (icmp_ln44_243_reg_1589 and and_ln44_166_fu_778_p2);
    and_ln44_170_fu_836_p2 <= (xor_ln44_137_fu_831_p2 and or_ln44_65_fu_826_p2);
    and_ln44_171_fu_842_p2 <= (tmp_217_reg_1577 and select_ln44_100_fu_808_p3);
    and_ln44_172_fu_859_p2 <= (xor_ln44_147_fu_853_p2 and tmp_214_reg_1566);
    and_ln44_173_fu_1023_p2 <= (xor_ln44_139_fu_1018_p2 and tmp_221_fu_1011_p3);
    and_ln44_174_fu_1048_p2 <= (xor_ln44_140_fu_1042_p2 and icmp_ln44_245_reg_1635);
    and_ln44_175_fu_1060_p2 <= (icmp_ln44_246_reg_1640 and and_ln44_173_fu_1023_p2);
    and_ln44_177_fu_1081_p2 <= (xor_ln44_143_fu_1076_p2 and or_ln44_67_fu_1071_p2);
    and_ln44_178_fu_1087_p2 <= (tmp_222_reg_1628 and select_ln44_104_fu_1053_p3);
    and_ln44_179_fu_1104_p2 <= (xor_ln44_150_fu_1098_p2 and tmp_219_reg_1617);
    and_ln44_180_fu_1232_p2 <= (xor_ln44_145_fu_1226_p2 and tmp_226_fu_1203_p3);
    and_ln44_181_fu_1257_p2 <= (xor_ln44_146_fu_1251_p2 and icmp_ln44_248_reg_1679);
    and_ln44_182_fu_1269_p2 <= (icmp_ln44_249_reg_1684 and and_ln44_180_fu_1232_p2);
    and_ln44_184_fu_1291_p2 <= (xor_ln44_149_fu_1286_p2 and or_ln44_69_fu_1280_p2);
    and_ln44_185_fu_1297_p2 <= (tmp_227_fu_1218_p3 and select_ln44_108_fu_1262_p3);
    and_ln44_186_fu_1315_p2 <= (xor_ln44_151_fu_1309_p2 and tmp_224_reg_1668);
    and_ln44_fu_533_p2 <= (xor_ln44_fu_528_p2 and tmp_211_fu_521_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln40_fu_340_p2)
    begin
        if (((icmp_ln40_fu_340_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter4_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, i_3_fu_128, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i <= i_3_fu_128;
        end if; 
    end process;

        conv7_i_1_cast_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i_1),32));

        conv7_i_2_cast_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i_2),32));

        conv7_i_3_cast_fu_296_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i_3),32));

        conv7_i_cast_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i),32));

    icmp_ln40_fu_340_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv3_4) else "0";
    icmp_ln44_240_fu_473_p2 <= "1" when (tmp_170_fu_463_p4 = ap_const_lv5_1F) else "0";
    icmp_ln44_241_fu_479_p2 <= "1" when (tmp_170_fu_463_p4 = ap_const_lv5_0) else "0";
    icmp_ln44_242_fu_702_p2 <= "1" when (tmp_12_fu_692_p4 = ap_const_lv4_F) else "0";
    icmp_ln44_243_fu_718_p2 <= "1" when (tmp_13_fu_708_p4 = ap_const_lv5_1F) else "0";
    icmp_ln44_244_fu_724_p2 <= "1" when (tmp_13_fu_708_p4 = ap_const_lv5_0) else "0";
    icmp_ln44_245_fu_947_p2 <= "1" when (tmp_14_fu_937_p4 = ap_const_lv4_F) else "0";
    icmp_ln44_246_fu_963_p2 <= "1" when (tmp_15_fu_953_p4 = ap_const_lv5_1F) else "0";
    icmp_ln44_247_fu_969_p2 <= "1" when (tmp_15_fu_953_p4 = ap_const_lv5_0) else "0";
    icmp_ln44_248_fu_1175_p2 <= "1" when (tmp_16_fu_1165_p4 = ap_const_lv4_F) else "0";
    icmp_ln44_249_fu_1191_p2 <= "1" when (tmp_17_fu_1181_p4 = ap_const_lv5_1F) else "0";
    icmp_ln44_250_fu_1197_p2 <= "1" when (tmp_17_fu_1181_p4 = ap_const_lv5_0) else "0";
    icmp_ln44_fu_457_p2 <= "1" when (tmp_s_fu_447_p4 = ap_const_lv4_F) else "0";
    mul_ln44_1_fu_508_p1 <= conv7_i_1_cast_reg_1483(16 - 1 downto 0);
    mul_ln44_2_fu_753_p1 <= conv7_i_2_cast_reg_1478(16 - 1 downto 0);
    mul_ln44_3_fu_998_p1 <= conv7_i_3_cast_reg_1473(16 - 1 downto 0);
    mul_ln44_fu_398_p1 <= conv7_i_cast_reg_1488(16 - 1 downto 0);
    or_ln44_64_fu_619_p2 <= (and_ln44_165_fu_614_p2 or and_ln44_163_fu_591_p2);
    or_ln44_65_fu_826_p2 <= (xor_ln44_136_fu_820_p2 or tmp_217_reg_1577);
    or_ln44_66_fu_864_p2 <= (and_ln44_172_fu_859_p2 or and_ln44_170_fu_836_p2);
    or_ln44_67_fu_1071_p2 <= (xor_ln44_142_fu_1065_p2 or tmp_222_reg_1628);
    or_ln44_68_fu_1109_p2 <= (and_ln44_179_fu_1104_p2 or and_ln44_177_fu_1081_p2);
    or_ln44_69_fu_1280_p2 <= (xor_ln44_148_fu_1274_p2 or tmp_227_fu_1218_p3);
    or_ln44_70_fu_1328_p2 <= (and_ln44_186_fu_1315_p2 or and_ln44_184_fu_1291_p2);
    or_ln44_71_fu_602_p2 <= (and_ln44_164_fu_597_p2 or and_ln44_161_fu_570_p2);
    or_ln44_72_fu_847_p2 <= (and_ln44_171_fu_842_p2 or and_ln44_168_fu_815_p2);
    or_ln44_73_fu_1092_p2 <= (and_ln44_178_fu_1087_p2 or and_ln44_175_fu_1060_p2);
    or_ln44_74_fu_1303_p2 <= (and_ln44_185_fu_1297_p2 or and_ln44_182_fu_1269_p2);
    or_ln44_fu_581_p2 <= (xor_ln44_130_fu_575_p2 or tmp_212_reg_1526);
    res_local_1_out <= res_local_1_fu_136;

    res_local_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln40_reg_1493_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln40_reg_1493_pp0_iter3_reg = ap_const_lv1_1))) then 
            res_local_1_out_ap_vld <= ap_const_logic_1;
        else 
            res_local_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    res_local_2_out <= res_local_2_fu_140;

    res_local_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln40_reg_1493_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln40_reg_1493_pp0_iter3_reg = ap_const_lv1_1))) then 
            res_local_2_out_ap_vld <= ap_const_logic_1;
        else 
            res_local_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    res_local_3_out <= res_local_3_fu_144;

    res_local_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln40_reg_1493_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln40_reg_1493_pp0_iter3_reg = ap_const_lv1_1))) then 
            res_local_3_out_ap_vld <= ap_const_logic_1;
        else 
            res_local_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    res_local_out <= res_local_fu_132;

    res_local_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln40_reg_1493_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln40_reg_1493_pp0_iter3_reg = ap_const_lv1_1))) then 
            res_local_out_ap_vld <= ap_const_logic_1;
        else 
            res_local_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln44_100_fu_808_p3 <= 
        and_ln44_167_fu_803_p2 when (and_ln44_166_fu_778_p2(0) = '1') else 
        icmp_ln44_243_reg_1589;
    select_ln44_103_fu_1036_p3 <= 
        icmp_ln44_246_reg_1640 when (and_ln44_173_fu_1023_p2(0) = '1') else 
        icmp_ln44_247_reg_1647;
    select_ln44_104_fu_1053_p3 <= 
        and_ln44_174_fu_1048_p2 when (and_ln44_173_fu_1023_p2(0) = '1') else 
        icmp_ln44_246_reg_1640;
    select_ln44_107_fu_1245_p3 <= 
        icmp_ln44_249_reg_1684 when (and_ln44_180_fu_1232_p2(0) = '1') else 
        icmp_ln44_250_reg_1691;
    select_ln44_108_fu_1262_p3 <= 
        and_ln44_181_fu_1257_p2 when (and_ln44_180_fu_1232_p2(0) = '1') else 
        icmp_ln44_249_reg_1684;
    select_ln44_109_fu_1320_p3 <= 
        ap_const_lv16_7FFF when (and_ln44_184_fu_1291_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln44_112_fu_625_p3 <= 
        ap_const_lv16_7FFF when (and_ln44_163_fu_591_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln44_113_fu_633_p3 <= 
        select_ln44_112_fu_625_p3 when (or_ln44_64_fu_619_p2(0) = '1') else 
        sum_1_reg_1521;
    select_ln44_114_fu_870_p3 <= 
        ap_const_lv16_7FFF when (and_ln44_170_fu_836_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln44_115_fu_878_p3 <= 
        select_ln44_114_fu_870_p3 when (or_ln44_66_fu_864_p2(0) = '1') else 
        sum_3_reg_1572;
    select_ln44_116_fu_1115_p3 <= 
        ap_const_lv16_7FFF when (and_ln44_177_fu_1081_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln44_117_fu_1123_p3 <= 
        select_ln44_116_fu_1115_p3 when (or_ln44_68_fu_1109_p2(0) = '1') else 
        sum_5_reg_1623;
    select_ln44_96_fu_563_p3 <= 
        and_ln44_160_fu_558_p2 when (and_ln44_fu_533_p2(0) = '1') else 
        icmp_ln44_240_reg_1538;
    select_ln44_99_fu_791_p3 <= 
        icmp_ln44_243_reg_1589 when (and_ln44_166_fu_778_p2(0) = '1') else 
        icmp_ln44_244_reg_1596;
    select_ln44_fu_546_p3 <= 
        icmp_ln44_240_reg_1538 when (and_ln44_fu_533_p2(0) = '1') else 
        icmp_ln44_241_reg_1545;
        sext_ln44_33_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_640_p3),32));

        sext_ln44_35_fu_893_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln44_s_fu_885_p3),32));

        sext_ln44_37_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln44_1_fu_1130_p3),32));

    shl_ln44_1_fu_1130_p3 <= (select_ln44_117_fu_1123_p3 & ap_const_lv11_0);
    shl_ln44_s_fu_885_p3 <= (select_ln44_115_fu_878_p3 & ap_const_lv11_0);
    shl_ln_fu_640_p3 <= (select_ln44_113_fu_633_p3 & ap_const_lv11_0);
    sum_1_fu_433_p2 <= std_logic_vector(unsigned(sum_fu_411_p4) + unsigned(zext_ln44_fu_429_p1));
    sum_2_fu_665_p4 <= add_ln44_fu_652_p2(26 downto 11);
    sum_3_fu_678_p2 <= std_logic_vector(unsigned(sum_2_fu_665_p4) + unsigned(zext_ln44_96_fu_675_p1));
    sum_4_fu_910_p4 <= add_ln44_114_fu_897_p2(26 downto 11);
    sum_5_fu_923_p2 <= std_logic_vector(unsigned(sum_4_fu_910_p4) + unsigned(zext_ln44_97_fu_920_p1));
    sum_7_fu_1213_p2 <= std_logic_vector(unsigned(sum_6_reg_1674) + unsigned(zext_ln44_98_fu_1210_p1));
    sum_9_fu_1334_p3 <= 
        select_ln44_109_fu_1320_p3 when (or_ln44_70_fu_1328_p2(0) = '1') else 
        sum_7_fu_1213_p2;
    sum_fu_411_p4 <= mul_ln44_fu_398_p2(26 downto 11);
    tmp_12_fu_692_p4 <= add_ln44_fu_652_p2(31 downto 28);
    tmp_13_fu_708_p4 <= add_ln44_fu_652_p2(31 downto 27);
    tmp_14_fu_937_p4 <= add_ln44_114_fu_897_p2(31 downto 28);
    tmp_15_fu_953_p4 <= add_ln44_114_fu_897_p2(31 downto 27);
    tmp_16_fu_1165_p4 <= add_ln44_116_fu_1142_p2(31 downto 28);
    tmp_170_fu_463_p4 <= mul_ln44_fu_398_p2(31 downto 27);
    tmp_171_fu_485_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_172_fu_730_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_173_fu_975_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_17_fu_1181_p4 <= add_ln44_116_fu_1142_p2(31 downto 27);
    tmp_210_fu_421_p3 <= mul_ln44_fu_398_p2(10 downto 10);
    tmp_211_fu_521_p3 <= mul_ln44_reg_1509(26 downto 26);
    tmp_213_fu_539_p3 <= mul_ln44_reg_1509(27 downto 27);
    tmp_216_fu_766_p3 <= add_ln44_reg_1560(26 downto 26);
    tmp_218_fu_784_p3 <= add_ln44_reg_1560(27 downto 27);
    tmp_221_fu_1011_p3 <= add_ln44_114_reg_1611(26 downto 26);
    tmp_223_fu_1029_p3 <= add_ln44_114_reg_1611(27 downto 27);
    tmp_226_fu_1203_p3 <= add_ln44_116_reg_1662(26 downto 26);
    tmp_227_fu_1218_p3 <= sum_7_fu_1213_p2(15 downto 15);
    tmp_228_fu_1238_p3 <= add_ln44_116_reg_1662(27 downto 27);
    tmp_fu_356_p10 <= ap_sig_allocacmp_i(2 - 1 downto 0);
    tmp_fu_356_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_s_fu_447_p4 <= mul_ln44_fu_398_p2(31 downto 28);
    trunc_ln40_fu_352_p1 <= ap_sig_allocacmp_i(2 - 1 downto 0);
    xor_ln44_128_fu_552_p2 <= (tmp_213_fu_539_p3 xor ap_const_lv1_1);
    xor_ln44_130_fu_575_p2 <= (select_ln44_fu_546_p3 xor ap_const_lv1_1);
    xor_ln44_131_fu_586_p2 <= (tmp_209_reg_1515 xor ap_const_lv1_1);
    xor_ln44_133_fu_773_p2 <= (tmp_217_reg_1577 xor ap_const_lv1_1);
    xor_ln44_134_fu_797_p2 <= (tmp_218_fu_784_p3 xor ap_const_lv1_1);
    xor_ln44_136_fu_820_p2 <= (select_ln44_99_fu_791_p3 xor ap_const_lv1_1);
    xor_ln44_137_fu_831_p2 <= (tmp_214_reg_1566 xor ap_const_lv1_1);
    xor_ln44_139_fu_1018_p2 <= (tmp_222_reg_1628 xor ap_const_lv1_1);
    xor_ln44_140_fu_1042_p2 <= (tmp_223_fu_1029_p3 xor ap_const_lv1_1);
    xor_ln44_142_fu_1065_p2 <= (select_ln44_103_fu_1036_p3 xor ap_const_lv1_1);
    xor_ln44_143_fu_1076_p2 <= (tmp_219_reg_1617 xor ap_const_lv1_1);
    xor_ln44_144_fu_608_p2 <= (or_ln44_71_fu_602_p2 xor ap_const_lv1_1);
    xor_ln44_145_fu_1226_p2 <= (tmp_227_fu_1218_p3 xor ap_const_lv1_1);
    xor_ln44_146_fu_1251_p2 <= (tmp_228_fu_1238_p3 xor ap_const_lv1_1);
    xor_ln44_147_fu_853_p2 <= (or_ln44_72_fu_847_p2 xor ap_const_lv1_1);
    xor_ln44_148_fu_1274_p2 <= (select_ln44_107_fu_1245_p3 xor ap_const_lv1_1);
    xor_ln44_149_fu_1286_p2 <= (tmp_224_reg_1668 xor ap_const_lv1_1);
    xor_ln44_150_fu_1098_p2 <= (or_ln44_73_fu_1092_p2 xor ap_const_lv1_1);
    xor_ln44_151_fu_1309_p2 <= (or_ln44_74_fu_1303_p2 xor ap_const_lv1_1);
    xor_ln44_fu_528_p2 <= (tmp_212_reg_1526 xor ap_const_lv1_1);
    zext_ln44_96_fu_675_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_215_reg_1555),16));
    zext_ln44_97_fu_920_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_220_reg_1606),16));
    zext_ln44_98_fu_1210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_225_reg_1657_pp0_iter4_reg),16));
    zext_ln44_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_210_fu_421_p3),16));
end behav;
